### ISSUE TITLE
BBT Getting Started Doku

### ISSUE THREAD

**Issue by lucashabersaat** [puzzle-bbt/bbt#1]
Dies soll ein allgemeiner Ausgangspunkt für neue Mitglieder im BBT sein. Vorallem in Hinblick mit der SBB und den vielen Lernenden, die bei uns arbeiten werden, ist diese Doku wichtig.

Das Readme.md im [puzzle/bbt](https://github.com/puzzle-bbt/bbt) repository soll der Ausgangspunkt werden.
Wirklich wichtig, es soll kurz, prägnant und stichwortartig geschrieben werden.

Es soll beinhalten:
* Scrum Dokumentation
* Projekt Repos
* Weiterführende Einführungs-Links wie Puzzle Wiki

**Comment by miosidler** [comment]
Finde die Doku sehr übersichtlich, hat mir persönlich viel geholfen. Vorschläge:

- Falls ein Scrumabschnitt mehrere Bezeichnungen hat, die dasselbe bedeuten, diese direkt beim Titel hinschreiben, vielleicht in kleinerer Schrift (zB. Story (aka. Issue, aka. Ticket)), damit man auf einen Blick sieht, welche Ausdrücke sich auf dasselbe beziehen

- Evtl. einen Vergleich zu Scrum nennen wie zB. das Wasserfallmodell (ohne Erläuterungen, nur den Namen)

- Evtl. Vorteile/Nachteile von Scrum ansprechen, vielleicht aber auch überflüssig da dies schon im verlinkten Video gemacht wird

**Comment by luca-bruegger** [comment]
Sehr gut geschrieben.Vorschläge Meinerseits:

- Die Bilder separat in einen Ordner legen z.b. /scrum/images.

- Bezüglich git vielleicht noch eine Referenz auf DOD.

- Bei der Checkliste des Sprint Meetings ist mir folgendes Aufgefallen:
    1. Punkt An- / Abwesenheiten kontrollieren könnte man den unteren Punkt *am Ende des Sprints* ersetzen durch *am Tag des Sprint Meetings*
    2. Bei dem Punkt Review Präsentation sollte man vielleich noch erwähnen dass diese nacheinander und nicht Parallel erstellt werden sollten. So kann man auch Merge Conflicts umgehen :)
    3. Beim Punkt Remote könnte man noch ein Tool fürs Remote Story schätzen vorschlagen. Das Tool von letzter Woche: https://www.scrumpoker-online.org/

-  Bei der Doku des Planungsfiles vielleicht noch eine Formel zur berechnung der Punkte des neuen Sprints :smile: (Ist nur bedingt relevant, da die Formeln im Planungsfile direkt angegeben sind, würde mir aber trotzdem beim verstehen helfen)

- Vielleicht das sprint_meeting_ablauf.md noch erweitern. Beispielsweise zum Punkt Retro noch ergänzen wie ein Retro Board aussieht (Wind, Steine, Insel, etc..) und noch das review_praesentation.md beim Review verlinken. Beim Punkt Planning vielleicht noch schreiben dass die Stories genau beschrieben werden sollten, da anhand der Beschreibung gearbeitet wird. 

Sonst finde die Doku :top: und wird sicher viel bei einem Einstieg in die Themen helfen :+1:
