### ISSUE TITLE
Taiga Daten untersuchen

### ISSUE THREAD

**Issue by njaeggi** [puzzle-bbt/bbt#131]
Die Daten von Taiga stimmen wahrscheinlich nicht mit den Daten von WeKan überein, deshalb müssen wir schauen welche Elemente es in Taiga gibt und ob es namentliche Abweichungen gibt.

- Unterschiede dokumentieren
- Struktur der Taiga Daten erfassen
- Mit Auftraggeber absprechen welche Daten übernommen werden
- Wo speichern wir das ganze ab -> abklären.

**Comment by MarcEgliP** [comment]
Dokumentation der Taiga Daten im JSON Format: 
https://codimd.puzzle.ch/fqK3RLPcR0edV0wgngIe9Q#
