### ISSUE TITLE
Daten einlesen Methode/Reihenfolge

### ISSUE THREAD

**Issue by njaeggi** [puzzle-bbt/bbt#133]
Überprüfen in welcher Reihenfolge die JSON Datei eingelesen werden kann, da eventuell Zusammenhänge mit anderen Teilen der Datei bestehen.

- Probieren und dokumentieren
- JSON Daten einzeln speichern -> kann dazu führen dass man JSON nicht von oben nach unten einlesen kann. 
- evtl. Reihenfolge einlesen der JSON Daten dementsprechend anpassen
- evtl. hat JSON Import von Taige eine bevorzugte Reihenfolge -> Doku lesen oder ausprobieren
- Am Schluss wissen wir wie die Reihenfolge sein muss

**Comment by MarcEgliP** [comment]
Der FileReader wurde erstellt und mit dem nötigne ExceptionHandling versehen. Zusätzlich haben @Eggimpa  und ich Tests für die FileReaderklasse erstellt. Ausserdem haben wir die Main methode mit einem try, catch Block versehen, in welchem nun die weiteren Schritte der Migration eingefügt werden. Bei diesen Schritten haben wir Unterstützung von @tuxmatta  erhalten
