### ISSUE TITLE
Starter implementieren mit Log Ausgaben

### ISSUE THREAD

**Issue by njaeggi** [puzzle-bbt/bbt#138]
Starter implementieren, der die mitgegebene Datei einliest und direkt die API Anfragen schickt. Dabei soll der aktuelle Stand geloggt werden, um zu sehen wo etwas schiefgelaufen ist.

- Controller von allem
- Main Klasse die man starten kann und das ganze dann startet
- Logging und Progress 
- Würde abbrechen falls etwas nicht klappt
_- Neustart muss möglich sein der dann weitermacht wo wir abgestürzt sind: wird nicht umgesetzt_

**Comment by MarcEgliP** [comment]
Der Starter ist momentan blockiert, da zuerst das Mapping fertiggestellt werden muss, um danach eine Methode zur Wiederaufnahme des Mappingprozesses bei Fehlern zu implementieren.
