### ISSUE TITLE
JSON verarbeiten

### ISSUE THREAD

**Issue by Robin481** [puzzle-bbt/bbt#139]
- JSON einlesen
- JSON Bibliothek dafür verwenden
- Daraus Datenmodell abfüllen
- Mappings dementsprechend verwenden ( bspw. WeKan Robin mit ID 35 -> Taiga Robin erstellen)
- Progress mitgeben an Controller
- Error-Handling falls etwas nicht klappt mit klaren Fehlermeldungen

**Comment by MarcEgliP** [comment]
Mapper Klasse wurde implementiert. Refactoring wird momentan gemacht, es soll folgendes Umgesetzt werden:
- Alle User sollen über einen UserService vor dem Mapping geholt werden und über Dependency Injection dem Mapper übergeben werden.
- BuilderKlassen für die Models erstellt werden und ihnen dann per Mapper die nötigen Datensätze per JSON übergeben werden.
- Alle Builderklassen sollen die Parentklasse "MigrationBuilder" besitzen. Darin sollen alle Methoden festgehalten werden, welche alle Builder benötigen.
