### ISSUE TITLE
Taiga Authorisierung

### ISSUE THREAD

**Issue by Robin481** [puzzle-bbt/bbt#140]
- Wie können wir die Daten an Taiga schicken
- Wie authentifizieren wir uns?
- Token? Login? API Key?
- Rücksprache mit /sys
- evtl. Technischer User erstellen
- Schnitstelle aufrufen und testen

**Comment by njaeggi** [comment]
Authentifizierung funktioniert, wir brauchen nur den technischen User um zu sehen ob das ganze auch auf der Puzzle Umgebung funktioniert.
