### ISSUE TITLE
Prozess der Erstellung loggen

### ISSUE THREAD

**Issue by MarcEgliP** [puzzle-bbt/bbt#156]

**Comment by MarcEgliP** [comment]
UserStory ist momentan geblockt, da alle Logs zweimal ausgegeben werden. Dies muss noch mit der Hilfe von @tuxmatta angeschaut werden.

**Comment by MarcEgliP** [comment]
Heute nehme ich noch einmal einen Anlauf und versuche das Problem des doppelten Loggens zu lösen.

**Comment by MarcEgliP** [comment]
Ich habe eine Möglichkeit gefunden wie wir die Logausgaben nur einmal machen können, jedoch werden die Nachrichten noch Rot ausgegeben. Deswegen muss noch zuerst Rücksprache mit @tuxmatta gemacht werden.

**Comment by tuxmatta** [comment]
Wird im 177 behandelt
