### ISSUE TITLE
Wekan Teilaufgaben übernehmen

### ISSUE THREAD

**Issue by tuxmatta** [puzzle-bbt/bbt#158]
Es soll nur die erste Ebene von Teilaufgaben übernommen werden. Bestehen im JSON-Export vom Wekan Teilaufgaben von Teilaufgaben, so sollen diese bei der Übernahme ausgegeben werden (LogLevel: WARN).

Im Taiga werden Teilaufgaben als Task einer UserStory erstellt.

**Comment by kcinay055679** [comment]
Mapping funktioniert  
Erste Tests sind im UserstoryProcessor vorhanden
Die Klasse Task ist jetzt die Parentklasse der Klasse UserStory selbiges gilt auch für die Processors.

Es treten noch Fehler beim Übermitteln der Request auf.
Die API Schnittstelle erwartet einen Statuscode welcher wechselt, die request um diesen abzurufen funktionniert nicht.

https://docs.taiga.io/api.html#tasks-list

Beim exportieren von Wekan Bords darauf achten das unter Subtasks settings das Häckchen bei Prefix with full path gesetzt ist.

**Comment by Eggimpa** [comment]
- für die Subtasks wird zwingend ein weiterer Export von Wekan benötigt, mit den Informationen zu den Subtasks.
- Müssen neue Stories geschätzt werden um den zweiten Mapper und die POST-request zu erstellen

**Comment by kcinay055679** [comment]
Sowohl das Einlesen des zweiten JSON's als auch die post request funktionieren.
Es fehlen aber noch tests und die Struktur des SubTask processor bzw des Userstory processor kann verbessert werden.
