### ISSUE TITLE
Fehlende Tests implementieren

### ISSUE THREAD

**Issue by tuxmatta** [puzzle-bbt/bbt#172]
Die Testabdeckung ist aktuell zu niedrig (ca. Class: 76%, Method: 40%, Line: 32%) und bei machen Java Klassen existieren keine Tests. Die fehlenden Tests erstellen.

**Soll-Abdeckung:** 
Class: 80%, Method: 80%, Line: 80%

**Comment by lkleisa** [comment]
Ich habe Tests für das User Model, den Request Service und den Mapper geschrieben. 
Wahrscheinlich müssen alle Tests nochmals verbessert werden, es sollten Mocks verwendet werden. 
Anschliessend habe ich mit den Tests für den WriteController gestartet. Dort habe ich mit Hilfe von Jonas von Anfang an mit Mocks gearbeitet. Ich konnte eine Methode völlig Testen (createProject). Mit addMemberToProject habe ich angefangen, es hat jedoch mit dem FakeReturn nicht geklappt.

**Comment by lkleisa** [comment]
Es gibt einen neuen HttpResponseBuilder, mitwelchem man den StatusCode und den Body eines Request Faken kann. 
Im WriteController müssen noch ein paar Änderungen vorgenommen werden. Zum Beispiel wird keine Migrationsexeption geworfen, wenn ein Parameter Null ist, welchen es braucht. Oder auch wenn der StatusCode nicht 200/201 ist, wird einfach 1 zurückgegeben. Dies muss noch verbessert werden.

**Comment by lkleisa** [comment]
Ich habe begonnen, die bestehenden Tests zu verbessern und mit Mockito zu arbeiten. Ich habe auf dem Branch https://gitlab.puzzle.ch/pitc_lehrausbildung/kleinprojekte/migration-wekan-taiga/-/tree/172-adapt-existing-tests mit dem AttachmentProcessor begonnen. Ich hatte anfangs Probleme, welche Klassen jetzt zu Mocken sind und welche Methoden überprüft werden müssen. 
2 Tests sind mit @Disabled markiert, diese sind noch nicht fertig, da ich es nicht geschafft habe, das notwendige zu testen. 2 Tests schlagen fehl. da sie eine MigrationsException erwarten bei mitgeben von null oder unvollständigen Daten. Diese Exception wird jedoch noch nicht geworfen im AttachmentProcessor

**Comment by njaeggi** [comment]
Tests für WriteController fast fertig. 73% abgedeckt
Nicht zu testen:
- createTaigaProject
- sendRequests
Noch offen:
- buildMutliformRequest
- buildMultipartData
- createAttachement
Zu beachten:
Tests auch auf fehlerfall prüfen (400 Responses, Null parameter) Beispiele bei den anderen Tests zu finden

Error Handling anpassen wenn noch keine Exceptions geworfen werden, wo nötig. Log Ausgaben bei fehlern und erstellen nicht vergssen

**Comment by MarcEgliP** [comment]
- Tests in AttachmentProcessorTest fertig (review erforderlich)
- Tests für SET-Methoden in allen ProcessorTests fertig 
- UserStoryProcessorTests noch nicht geschrieben
- Processor Methode bei allen Processor Tests mocken

**Comment by Eggimpa** [comment]
- RequestServiceTest: Mocken oder nicht? Effektive Request oder nicht?

**Comment by lkleisa** [comment]
- AttachmentProcessorTest review ist gemacht
- Alle Tests sind bis auf folgende fertig, evt absprache mit Jonas ob gut so 
  - WriteController (Niklas)
  - UserStoryProcessor (Yanick machte noch Änderungen)
  - ReadController (Muss noch verbessert werden)
  - Mapper (Begonnen auf branch 172-implement_missing_tests in einem eigenen File)
