### ISSUE TITLE
Mapping users

### ISSUE THREAD

**Issue by kcinay055679** [puzzle-bbt/bbt#179]
Abrufen aller Puzzlemembers mit der anschliessenden Zuordnung zu der entsprechenden Wekan ID. 
List aller Members (E-mail, Username, Taiga id)

**Comment by MarcEgliP** [comment]
Dieses Label ist geblockt, solange wir keine Userliste von dem Sys-Team bekommen haben. Am 16.08.22 habe ich nochmals bei  Sys im Bezug auf die Liste nachgefragt, es hiess, daran werde noch gearbeitet.

**Comment by njaeggi** [comment]
Wie haben eine Liste mit allen Usern aus dem Taiga, habe sie allen die ma Projekt selbst mitarbeiten per mail weitergeleitet. Wir haben noch eine Liste mit Username/Passwort angefragt, diese aber noch nicht bekommen
