### ISSUE TITLE
Lokale Entwicklungsumgebung vorbereiten

### ISSUE THREAD

**Issue by ThePiOu** [puzzle-bbt/bbt#185]
Das lokale Setup vom FMSX Projekt ist etwas aufwändig. Wegen der Komplexität des Projekts sowie der beschränkten Erweiterung macht es keinen Sinn, dass gesamte Entwicklerteam einzubeziehen. Die genaue Aufteilung werden wir miteinander besprechen.

Ziel dieser Story ist es, dass wir bei min. zwei Mitarbeitern das FMSX Projekt erfolgreich aufgesetzt haben und das die Grundzüge des FMSX verstanden sind.

Lokale Installation bereit:
* [x] Paco
* [x] Lias
* [x] Niklas

**Comment by lkleisa** [comment]
Bei mir läuft das ganze jetzt lokal. MockLok kann gewünschte Events senden und diese werden im HUB angezeigt.
Fehler hatte ich beim settings.xml file und den Anforderungen.
