### ISSUE TITLE
Aktueller Code von BLS in Puzzle Repo holen

### ISSUE THREAD

**Issue by ThePiOu** [puzzle-bbt/bbt#186]
Der aktuelle Programmcode von FMSX befindet sich in einem BLS-Repo. Ein aktueller Stand wird von Jonas in das Puzzle Repo (https://gitlab.puzzle.ch/pitc_fmsx) übernommen.

- [x] aktueller Code von BLS syncen
- [x] Wenn nötig mergen
- [ ] Neuster Stand zum Laufen bringen

**Comment by tuxmatta** [comment]
Die Änderungen von Michael Zaugg für den Switch von AWE zu Cloudscale bei Puzzle sind auf den develop Branch gemerged.
Der Stand vom develop Branch der BLS ist in den develop Branch von Puzzle übernommen worden.
