### ISSUE TITLE
Weiterführung Usermapping

### ISSUE THREAD

**Issue by Eggimpa** [puzzle-bbt/bbt#194]
Die Migration muss auch stattfinden wenn ein Wekan Member nicht auf Taiga Vorhanden ist, sowohl Externe wie auch Interne. Weiter müssen Externe User auch auf dem Board vorhanden sein, sofern sie einen Taiga Account haben. 

- [x] Migration findet statt, wenn Member nicht auf Taiga Registriert ist (Id wird auf Null gesetzt wo notwendig)
- [x] Migration findet statt wenn Externe keinen Taiga User haben. (Id wird auf Null gesetzt wo notwendig)
- [x] Migration findet statt wenn Externe bereits einen Taiga User haben. Alle Positionen werden richtig gesetzt. 
- [x] Franziska Hashim hat geheiratet, Sie hiess früher Franziska Bader, deshalb muss eine Lösung gefunden werden fbader auf fhashim zu mappen.  --> per search and replace vor jeder Migration
- [x] Logausgaben müssen noch fertiggestellt werden

**Comment by lkleisa** [comment]
User, welche nicht in der AllPuzzleUser list sind, werden auf der Konsole ausgegeben und deren id wird uf null gesetzt. 
Jetzt muss im UserService noch überprüft werden, ob die id null ist und wenn ja, dieser user nicht migriert wird. 
TODO auf UserService:79

**Comment by lkleisa** [comment]
Aktueller Code auf dem Branch #194-Witerführung-Usermapping

**Comment by MarcEgliP** [comment]
Alle User werden jetzt wirklich auf null gesetzt und aus der users Liste im UserService rausgefiltert. Alle usernames der rausgefilterten user befinden sich in der unregisteredUsernames Liste.

**Comment by MarcEgliP** [comment]
Gemacht werden muss: 
- [ ] Log Ausgaben wo ein unregistrierter User zugefügt wird: z.B. bei den Userstories.

Beschreibung: 
 Hier kann überprüft werden ob das JSON Stückchen welches wir bekommen einen Benutzernamen hat, welchen sich in der unregisteredUsernames Liste befindet. Wenn ja diese User per Log ausgeben.

Logmuster:
Was ist passiert:  Variabel => Wert
User couldn't be set: User => mschmid, Userstory => Haus aufräumen.
