### ISSUE TITLE
Maven Abhängigkeiten aufräumen

### ISSUE THREAD

**Issue by tuxmatta** [puzzle-bbt/bbt#200]
Als Entwicklungsteam wollen wir die Abhängigkeiten des Projekts so sauber wie möglich halten, um Konflikte bei den Libraries zu vermeiden.

1. Unnötige Abhängigkeiten im pom.xml löschen.
1. Nur noch eine JSON-Library im Projekt verwenden. (https://github.com/FasterXML/jackson-docs)

**Comment by MarcEgliP** [comment]
Vorgehen:
- [ ] Ungebrauchte Maven Abhängigkeiten löschen
- [ ] Versionen der Abhängigkeiten überprüfen, upgraden wo nötig
- [ ] Nur noch 1 JSON-Library verwenden, diese in den Klassen aktualisieren.

**Comment by MarcEgliP** [comment]
Was noch gemacht werden muss:
- Alle Tests durchlaufen lassen, die restlichen 3, 4 Tests welche fehlschlagen korrigieren.
- Eine property welche null ist und mit put auf ein JSONObject gesetzt wird, ist nicht darauf vorhanden -> abklären ob dies Probleme verursacht
- Schlussendlich muss das Programm laufen gelassen und überprüft werden ob alle Elemente im Taiga erstellt werden.
