### ISSUE TITLE
Tests fertigstellen

### ISSUE THREAD

**Issue by Eggimpa** [puzzle-bbt/bbt#203]
Alle Tests sollen fertiggestellt werden und funktionieren. Die folgenden Tests müssen noch implementiert werden:
- [x] UserServiceTest (Yanick hat begonnen)
- [x] UserStoryProcessorTest (Lias hat begonnen)
- [x] SubtaskProcessorTest  (Marc hat begonnen)

**Comment by lkleisa** [comment]
Ich habe auf dem Branch https://gitlab.puzzle.ch/pitc_lehrausbildung/kleinprojekte/migration-wekan-taiga/-/tree/fix_userstoryprocessor_test die alten Tests für den UserStoryProcessor umgeschrieben und verbessert. Weiter habe ich neue Tests geschrieben für alle Methoden. 
3 Tests sind mit @Disabled markiert, da es einen Bug gibt, welcher diese methoden beeinflusst. Dieser ist im Ticket #204 beschrieben. 
1 Test auf Line 195 im UserStoryProcessorTest funktioniert nicht, da eine ArrayIndexOutOfBounds Exception geworfen wird und wir eigentlich eine MigrationException erwarten. 
@MarcEgliP kannst du dies bitte anschauen, du hast die Mehtode geschrieben (setSwimlane())

**Comment by MarcEgliP** [comment]
Vorgehen für SubTaskProcessorTests:
- [ ] Tests für setter mit richtigem aber auch mit null Werten schreiben.
- [ ] Wenn andere Methoden vorhanden, diese mit Mockito testen.
- [ ] Alle Tests durchlaufen und reviewen lassen.
