### ISSUE TITLE
Filegrösse bestimmen von Attachments

### ISSUE THREAD

**Issue by Eggimpa** [puzzle-bbt/bbt#206]
Um zu sehen, welche Attachments von uns auf Taiga migriert werde können, brauchen wir eine Methode,  welche die Filegrösse bestimmt. 
## Vorgehen
- [x] Attachments auslesen und in einer Liste abspeichern
- [x] Attachments builden
- [x] Grösse der Attachments auslesen
- [x] Attachments, welche grösser als 1 MB sind ausgeben 
- [x] Alle Attachments, welche 1MB oder grösser sind auf Nextclooud laden und Link dazu in den Attachments einfügen

**Comment by Eggimpa** [comment]
Ist auf Blocked, weil wir einen Authentifizierungstoken von Sys brauchen für den upload auf nextcloud.

**Comment by njaeggi** [comment]
Noch Probleme beim einbinden von NextCloud, werde am Montag weiter machen:
Beste gefundene Methode bisher kommt von:
https://github.com/lookfirst/sardine

Im Moment bekommt man jedoch noch eine 443 Response zurück und ich konnte bisher noch nicht herausfinden weshalb.

**Comment by kcinay055679** [comment]
Speichern auf nextcloud funktionniert soweit.
Die Dateien werden in der nextcloud in den korrekten Verzeichnissen abgelegt (Projekt/Userstory).
Funktionen welche noch nicht getestet sind; 
createRequiredFolder
folderRequired
userStoryFolderRequired
hasLargeSubTaskAttachments
hasLargeFile
