### ISSUE TITLE
Migration von Swissflirt Monthly

### ISSUE THREAD

**Issue by Eggimpa** [puzzle-bbt/bbt#215]
Mark Waber möchte das Board Hitobito Swissflirt Monthly von Wekan nach Taiga migriert haben, damit die Benutzer dieses Board im Taiga arbeiten können.

## Zu Beachten: 
- André Kunz muss in Taiga registriert sein. 
- fbader zu fhashim wechseln im JSON Export
- dbrander, sraez, azimmermann müssen nicht importiert werden. 

#### Vorgehen
1. Mit Wekan Board Owner Zeitplan zur Migration vereinbaren
1. JSON-Export durch Paco Eggimann ausführen lassen
1. Migration auf Taiga Testsystem
1. Kontrolle der importierten Daten mit dem Board Owner
1. Finaler JSON-Export veranlassen
1. Finale Migration auf Taiga Produktion
1. Finale Kontrolle mit dem Kunden

#### Akzeptanzkriterien
* [x] Die Migration ist mit dem Kunde geplant
* [ ] Board ist erfolgreich migriert
* [ ] Abnahmen beim Kunde ist umgesetzt

**Comment by Vakmeth** [comment]
Vorgehen: 
- [x] Testmigration mit Nicole Frey besprechen
- [x] Falls gut, Migration auf Produktion durchführen
- [x] Nach Migration, Adminrechte vergeben (Rückfrage wer Admin?)
- [x] Finale Kontrolle
- [x] Technischer User entfernen
- [x] Log Anschauen und überprüfen wer nicht gemapped wurde, dies melden.
