### ISSUE TITLE
Taiga User brauchen Zugriff auf Nextcloud

### ISSUE THREAD

**Issue by Eggimpa** [puzzle-bbt/bbt#218]
Um die Attachments auf Nextcloud zu laden bei der Migration, muss der Taiga-Test und der Taiga-Produktions User zugriff auf nextcloud erhalten.

- [x] User braucht 2FA mit Key, bei Sys holen und einrichten. 
- [x] Taiga User wieder im Projekt Implementieren

**Comment by Vakmeth** [comment]
Ich bin bei /sys vorbeigegangen, da wurde mir gesagt das Lars Kehrli mir schreib, sollte er einen Key finden oder keinen mehr Vorrat haben.

**Comment by Vakmeth** [comment]
Die Zwei user besitzen nun einen Security-Key welcher auf der grossen Komode neben Pacos Pult abgeholt werden kann. Beide Keys befinden sich je in einem Säckchen welches jeweilig mit Test oder Production beschrieben ist. Da beide Keys nun konfiguriert sind, müssen die Taiga User nur noch im Projekt implementiert werden.
