### ISSUE TITLE
Description anpassen

### ISSUE THREAD

**Issue by Eggimpa** [puzzle-bbt/bbt#219]
Zur Zeit muss der User die Attachments herunterladen, anschliessend muss er den Link öffnen, damit er auf die Attachments zugreiffen kann. Die Idee ist jedoch, dass der Link klickable in der Description sein soll, damit er direkt auf das Attachments kommt. 

- [x] Alle Attachments sollen auf Nextcloud abgelegt werden, dabei soll ein Klickable Link ganz unten in die Discription, wodurch man direkt auf die Files gelangt. 
- [x] Die Checklisten sollten in die Discription mit linien abtrennen mit "***" 
- [x] Description abtrennen, mit dem "***" command für Linie.

**Comment by Vakmeth** [comment]
Vorgehen: 
- [x] Zuerst werde ich die Checkliste in die Description einfügen, da ich die Erstellung für die Checklisten geschrieben habe und so dort wahrscheinlich am schnellsten bin.
- [x] Danach die Attachments, da Yanick heute noch hier ist und ich so bei Fragen auf ihn zukommen kann.
- [ ] Die Formatierung selbst werde ich bei den oberen Schritten immer wieder aktualisieren.
