### ISSUE TITLE
Nextcloud Datei User unabhängig anzeigen

### ISSUE THREAD

**Issue by kcinay055679** [puzzle-bbt/bbt#223]
**Describe the bug**
Eine Datei auf Nextcloud kann nur von dem User geöffnet werden, der diese auch erstellt hat.

**To Reproduce**
1. Neues Taiga Projekt erstellen
2. Attachmentlink in inkognitobrowser öffnen
3. Mit eine Nextcloud user anmelden mit dem die Datei NICHT erstellt wurde.
=> Datei wird nicht geöffnet

**Expected behavior**
Nach dem einloggen soll unabhänig vom eingeloggten User die Datei angezeigt werden.
Soll jedoch nicht im Root-Verzeichnis von files.puzzle.ch landen und nur für Boardmembers ersichtlich sein.

**Comment by kcinay055679** [comment]
Nextcloud bietet die Möglichkeit einen share-link pro Datei zu erstellen.
Mit diesem ist es unrelevant welcher User eingeloggt ist.
[Docs](https://docs.nextcloud.com/server/latest/developer_manual/client_apis/OCS/ocs-share-api.html)

**Comment by kcinay055679** [comment]
Neuer Link wird erstellt.
Nur Personen welche auch einen Account auf files.puzzle.ch haben, könnten die Datei auch anzeigen.
Alle Tests funktionnieren wieder ausser WriteControllerTest.createDescription()

**Comment by Vakmeth** [comment]
Vorgehen:
- [x] Veränderungen am WriteController genauer anschauen
- [x] Test untersuchen, Fehlerquelle finden

Anmerkung:
In der Kommunikation mit Yanick wurde mir gesagt das dieses Feature bis auf den einen Test fertig ist. Da ich den Test ursprünglich geschrieben habe, nehme ich mir nun der Sache an versuche den Test zu fixen.

**Comment by Vakmeth** [comment]
Ich habe den Test nun behoben und Yanick zur Verfügung gestellt. Dieser wird ihn beim nächsten Merge in den main einfügen.

**Comment by kcinay055679** [comment]
Die Nextcloud API wurde  höchstwahrschlich aktualisiert. 
Der Code wurde entsprechend angepasst.
Alle Dateien werden jetzt in /misc/taiga geladen.
Es wurde bei Sys nachgefragt ob das so okay sei. 
Wenn dem so ist kann der Branch in den main gemergt werden.

Ticket Sys:
https://help.puzzle.ch/#ticket/zoom/5240
