### ISSUE TITLE
BurningOKR - Datenbank-Schema dokumentieren

### ISSUE THREAD

**Issue by tuxmatta** [puzzle-bbt/bbt#229]
Als **Entwickler** möchte ich das Datenbank-Schema verstehen und dokumentieren, damit wir Erweiterungen an der DB vornehmen können.

#### Akzeptanzkriterien
* [ ] Datenbank-Schema ist dokumentiert (Textuell oder als PlantUML Diagramm)
* [ ] Aufbau der Datenbank ist verstanden

**Comment by Vakmeth** [comment]
Vorgehen:
- [x] Dokumentation zu der Datenbank
- [x] Versuchen Datenbankverbindung aufzubauen
- [ ] Bei erfolgreicher Verbindung den Aufbau der Datenbank Schritt für Schritt dokumentieren.

Link zu der Dokumentation: https://codimd.puzzle.ch/K2eRIjesRwiaYrAZ7Wr_iQ#

**Comment by Vakmeth** [comment]
**Gemacht wurde:**

Ich habe bis jetzt alle die Haputorganisations, Ziele und Teiltasks erfasst. Ausserdem habe ich auch die Kommentartabelle dokumentiert.

**Was gemacht werden muss:**

Genauer dokumentiert sollte das Team werden welches ebenfalls in der "okr_unit" Tabelle aufgeführt ist (siehe Dokumentation). Hier soll noch dokumentiert werden wo die Members des jeweiligen Teams aufgeführt sind und in welcher Tabelle der OKR-Master aufgeführt ist. Danach muss weiter überprüft werden was in der Dokumentation noch vorhanden sein muss (allenfall mit @tuxmatta )

Als Checkliste: 
- [x] Dokumentation die bis jetzt gemacht wurde durchlesen und verstehen.
- [x] Projekt lokal aufsetzen und Datenbankverbindung mit Datagrip bewerkstelligen (Credentials unter "BurningOKR/docs/postgres_install_docker.md" zu finden)
- [x] Weiterführung der Dokumentation (Insbesondere der Teams)
- [x] Abklären welche Komponente der Datenbank sonst noch dokumentiert werden sollten.

**Comment by kcinay055679** [comment]
Teams wurden dokumentiert.
Da die Websocket Verbindung nicht funktionniert können keine Aufgaben erstellt werden, das heisst es ist nicht möglich mit diesen zu interagieren.
