### ISSUE TITLE
BurningOKR - Datenmodell im Backend dokumentieren

### ISSUE THREAD

**Issue by tuxmatta** [puzzle-bbt/bbt#230]
Als **Entwickler** möchte ich das Datenmodell im Backend verstehen und dokumentieren, damit wir Erweiterungen am Datenmodell vornehmen können.

#### Akzeptanzkriterien
* [x] Dokumentiert, welche Java-Klassen/Packages das Datenmodell repräsentieren
* [x] Werden diese Klassen ev. generiert?
* [x] Aufbau und Verbindungen des Datenmodell ist verstanden

**Comment by lkleisa** [comment]
Im schon bestehenden Codi haben wir die Java Klassen dokumentiert, welche das Datenmodell repräsentieren: 
https://codimd.puzzle.ch/K2eRIjesRwiaYrAZ7Wr_iQ?view
Java Klassen werden keine automatisch generiert.
