### ISSUE TITLE
BurningOKR - Schnittstelle dokumentieren

### ISSUE THREAD

**Issue by tuxmatta** [puzzle-bbt/bbt#231]
Als **Entwickler** möchte ich die Schnittstelle zwischen Frontend und Backend verstehen und dokumentieren, damit wir Erweiterungen an dieser Schnittstelle vornehmen und die Funktionsweise des Tools besser verstehen können.

Hinweis:
Habe auch eine WebSocket Schnittstelle gefunden. Diese auch dokumentieren.

#### Akzeptanzkriterien
* [ ] Schnittstelle ist dokumentiert (Textuell und/oder als PlantUML Diagramm)
* [ ] Zusammenspiel zwischen Frontend und Backen ist verstanden

**Comment by kcinay055679** [comment]
https://codimd.puzzle.ch/K2eRIjesRwiaYrAZ7Wr_iQ?both
