### ISSUE TITLE
Ausbildung - Spring Framework Marc

### ISSUE THREAD

**Issue by peggimann** [puzzle-bbt/bbt#236]
Wir wollen nun das Springframework kennenlernen, dabei gilt das Lernticket als erfüllt wenn die folgenden Abschnitte bearbeitet und verstanden wurden: 
 - [x] Einfaches Spring Projekt erstellen
 - [x] Building a RESTful Web Service 
 - [x] Console Application für Accessing Data with JPA 
 - [x] WebService for Accessing JPA Data with REST mit Hilfe von HATEOAS
 - [x] Creating API Documentation with Restdocs und ASCIIdoc.
- [x] Securing a Web Application
- [x] How to Use Named Queries with Spring Data JPA

Weitere Informationen findet ihr in dem folgenden Codi :
https://codimd.puzzle.ch/Ub_y9bQpTTyJzm0yN1qRQw#

**Comment by Vakmeth** [comment]
Vorgehen für die ersten 2 Punkte:
- [x] Spring Projekt mit Spring Initializr kreieren, dieses in Github Repository laden.
- [x] Anhand des Codis und der API von Spring Boot den RESTful Web Service implementieren
- [x] Alle Erkenntnisse und Schwierigkeiten fortlaufend in ein Codi schreiben.

**Comment by Vakmeth** [comment]
Nächstes Ziel für den Punkt 3: Accessing Data mit JPA
- [x] Testentities erstellen
- [x] Request anpassen, so dass er ein Gemüse erstellt
- [x] Schema.sql und Data.sql files einfügen um damit mit foreign Keys auf andere Daten zeigen zu können.
- [x] @NonNull Annotation testen

**Comment by Vakmeth** [comment]
Sowohl die Anbindung zu einer eingebetteten Datenbank wie auch die Validierung für null Werte steht. Nun kommt der nächste Teil:

- [x] Über das Spring Tutorial HATEOS kennenlernen
- [x] Allenfalls eigene Erkenntnisse dazu nachtragen
- [x] Prinzip / Vorgehen davon im Projekt einbauen

**Comment by Vakmeth** [comment]
Ein Repository wird nun über die Spring-Data-Rest-Webmvc dependency angesprochen, das andere Repository wird über das normale Vorgehen mit einem Controller verwaltet. Als nächstes gilt es eine Dokumentation für die API mit Spring Rest Docs zu erstellen, dafür die Ziele:
- [x] Tutorial von Spring durcharbeiten, Ungeklärtes googeln und in Codi festhalten
- [x] Dokumentation in Projekt für den nötigen Controller implementieren (Vegetables)
- [x] Erste Einträge in Lerndokumentation überführen

**Comment by Vakmeth** [comment]
Ziel für die Spring Security:
- [x] Danach mit Verbesserung der Models anfangen: Mehr Models erstellen, für diese je nach Sinnvollkeite Spring Data Rest Webmvc verwenden oder nach altem Vorgehen arbeiten
- [x] Für alle Controller Tests schreiben (MockMVC), und wo nötig und sinnvoll Tests in die Dokumentation einfügen
- [x] Das Tutorial durcharbeiten, Fragen oder Schwierigkeiten aufschreiben
- [x] Spring Security einbauen

**Comment by Vakmeth** [comment]
Wird momentan durch die MigrationsTask #244 blockiert

**Comment by Vakmeth** [comment]
Ich konnte nun die User, welche auch schon vorher in der Datenbank waren, in die Security einfügen. Somit ergeben sich die nächsten, folgenden Ziele:
- [x] Named Queries Teil durchgehen, in Projekt einbinden
- [x] Techtalk über das Thema "Spring Repositories" vorbereiten
