### ISSUE TITLE
Ausbildung - Angular (Marc)

### ISSUE THREAD

**Issue by tuxmatta** [puzzle-bbt/bbt#240]
Als **Entwickler** möchte ich Angular besser verstehen und anwenden können, damit ich in Zukunft technisch sehr gut funktionierende und sauber getestete Angular WebApplikationen erstellen kann.

Folgenden Themen wollen wir bearbeitet und verstehen: 
- [x] REST-Schnittstelle definieren und umsetzen
- [x] Angular WebApplikation planen und umsetzen

Weitere Informationen findet ihr in dem folgenden Codi :
* [Lernziel: Angular](https://codimd.puzzle.ch/mvV7omfwQvCqrX5AQzdfzw)
* [Lernziel: REST + RESTful](https://codimd.puzzle.ch/MMbOOI-4R6ODCZMA7oIUYw)

**Comment by Vakmeth** [comment]
Ich habe das Dokument zu REST durchgelesen und dazu eine Zusammenfassung erstellt, welche die für mich wichtigsten Aspekte beinhaltet. Für gewisse Kriterien wie z.B. den Filter habe ich direkt eine Implementation in meinem Spring Projekt erstellt um zu testen wie ich die Parameter bekommen kann.

**Comment by Vakmeth** [comment]
Das weitere Vorgehen ist: 
- [x] Angular Tutorial folgen
- [ ] Tutorial beenden, Dokumentation für Lerndoku ergänzen
- [ ] Eigene Recherchen zum Thema Angular anstellen, Applikation ausbauen.
