### ISSUE TITLE
Erfasser von Kommentaren sollen ersichtlich sein

### ISSUE THREAD

**Issue by peggimann** [puzzle-bbt/bbt#244]
Um bei der Migration die Chronologie beizubehalten wollen wir die Verfasser der Kommentare ebenfalls in den Kommentaren via String einfügen. Im String soll lediglich der Username vom Wekan Board stehen.

 - [x] Username ist im String auf Board enthalten, egal ob gemappter user oder nicht
- [x] Tests sind geschrieben

**Comment by Vakmeth** [comment]
Der Verfasser des Kommentares ist nun ersichtlich und das JSON Originalfile wird nicht mehr mehrmals eingelesen, sondern eine Kopie von ihm erstellt. Ebenfalls sind alle Tests gefixed, so dass die Pipeline wieder erfolgreich durchläuft.

Noch nicht gemacht sind zusätzliche Tests für das Feature, welche ich morgen noch implementieren werde.
