### ISSUE TITLE
Angular Directives verstehen

### ISSUE THREAD

**Issue by tuxmatta** [puzzle-bbt/bbt#246]
Als Entwickler möchte ich Angular Directives besser verstehen, damit ich anschliessend das Angular Frontend effizient umsetzen kann.

Links zu der Dokumentation:
* https://angular.io/guide/built-in-directives
* https://angular.io/guide/attribute-directives
* https://angular.io/guide/structural-directives

Erfülle die Akzeptanzkriterien:
* [x] Lias: Ja sicher
* [x] Marc: Klar
* [x] Niklas: No Problem
* [x] Yanick: Was für eine Frage

#### Akzeptanzkriterien
* [ ] Alle verstehen die Build-in Directives
* [ ] Alle verstehen die Attribute Directives
* [ ] Alle verstehen die Structural Directives

**Comment by Vakmeth** [comment]
Ich habe nun die Build-in Directives durchgearbeitet und dazu eine eigene kleine Dokumentation als Nachschlagewerk angefertigt.

Dokumentation: https://codimd.puzzle.ch/oPTi9JwLTwyCrHAJ2zCipg#

Weiteres Vorgehen:
- [x] Angular Attribute Directives durchlesen
- [x] Dokumentation anfertigen und als Comment im Ticket hinterlegen

**Comment by Vakmeth** [comment]
Die Attribute Directives habe ich nun ebenfalls durchgelesen und wieder in einer Dokumentation zusammengefasst:

Doku: https://codimd.puzzle.ch/DSKX7hbpSietxNFI2-MF5g#

Weiteres Vorgehen:

- [x] Angular Structural Directives durchlesen
- [x] Doku dazu anfertigen
- [x] Ticket abschliessen

Doku Structural Directives: https://codimd.puzzle.ch/sWQG8MbpStSs80JtfqQKYA?both#

**Comment by lkleisa** [comment]
Ich habe alle Dokus durchgearbeitet und das Wichtigste in meine Lerndoku übernommen. Ich habe in meiner Angular App verschiedene Sachen ausprobiert.
