### ISSUE TITLE
Angular Template verstehen

### ISSUE THREAD

**Issue by tuxmatta** [puzzle-bbt/bbt#247]
Als Entwickler möchte ich Angular Template besser verstehen, damit ich anschliessend das Angular Frontend effizient umsetzen kann.

Links zu der Dokumentation:
* https://angular.io/guide/template-overview

Erfülle die Akzeptanzkriterien:
* [x] Lias: Ja sicher
* [x] Marc: Klar
* [x] Niklas: No Problem
* [x] Yanick: Was für eine Frage

#### Akzeptanzkriterien
* [ ] Alle verstehen die Funktionsweise von Templates
* [ ] Alle verstehen das Binding der Templates
* [ ] Alle verstehen der Gebrauch von Pipes
* [ ] Alle kennen die Möglichkeit SVG direkt im Template zu verwenden

**Comment by Vakmeth** [comment]
Vorgehen: 

- [x] Dokumentation von Angular durchlesen
- [x] Zusammenfassung schreiben und hinterlegen
- [x] Ticket abschliessen

Dokumentation: https://codimd.puzzle.ch/IhBsVGUhQ3iA3pHsJeQ_Yw#
