### ISSUE TITLE
Angular Components verstehen

### ISSUE THREAD

**Issue by tuxmatta** [puzzle-bbt/bbt#248]
Als Entwickler möchte ich Angular Components besser verstehen, damit ich anschliessend das Angular Frontend effizient umsetzen kann.

Links zu der Dokumentation:
* https://angular.io/guide/component-overview

Erfülle die Akzeptanzkriterien:
* [x] Lias: Ja sicher
* [x] Marc: Klar
* [x] Niklas: No Problem
* [x] Yanick: Was für eine Frage

#### Akzeptanzkriterien
* [ ] Alle verstehen die Interaktion mit Komponenten
* [ ] Alle verstehen die Komponenten Lifecycles
* [ ] Alle verstehen das Stylen von Komponenten und die Kapselung der Komponente

**Comment by Vakmeth** [comment]
Vorgehen: 

- [x] Dokumentation von Angular durchlesen
- [x] Eigene Zusammenfassung schreiben
- [x] Link zur Doku hinterlegen und Ticket abschliessen

Doku: https://codimd.puzzle.ch/OhCDJfDmRlmcGFrK-8hH2A#

**Comment by lkleisa** [comment]
Ich habe die verlinkte Dokumentation durchgelesen und alles soweit verstanden. Die Akzeptanzkriterien kann ich noch nicht erfüllen, da ich noch nicht alles vollständig verstanden & gelesen habe. Dies würde ich am Freitag machen.
