### ISSUE TITLE
OKR - Implementieren der verschiedenen Entity Objekte

### ISSUE THREAD

**Issue by tuxmatta** [puzzle-bbt/bbt#249]
Als Puzzle möchte ich die Entity Objekte für das OKR-Tool erstellen, damit man die OKRs abspeichern kann.

Diese Story hat mehrere Sup-Stories zum Umsetzung.

GIT Repo: github/puzzle/okr

#### Akzeptanzkriterien
* Alle Entity Objekte sind nach dem Schema umgesetzt
* Datenbank PostgreSQL, lokal als Docker Instanz
* Beim Start des Projekts sollte das Schema der DB jeweils neu erstellt und mit Testdaten gefüllt werden

**Comment by Vakmeth** [comment]
Branch:
https://github.com/puzzle/okr/tree/249-entities

Stand: 
- Spring Projekt + Projektstruktur wurde integriert
- Alle Entities wurden erstellt
- Die verlangten Methoden wurden mithilfe von Intellij automatisch implementiert, überprüfung von @tuxmatta oder @peggimann erwünscht
- Die Validators wurden nach befinden ausgewählt, bspw. wurden alle foreign-keys mit @NotNull annotiert und Titel auf 3 bis 20 Zeichen beschränkt
- Das ganze Schema ist bei Start auf http://localhost:8080/h2-console/ abrufbar, username und password steht in application.yml

Unklarheiten: 
- Feld: initiatives, Tabelle: Measure
Dieses Feld habe ich als Startwert interpretiert, weswegen ich es nur bei den Childklassen Textremeasure und Percentmeasure hinzugefügt habe, da das Booleanmeasure nur zwei Zustände kennt.

- Feld: unit, Tabelle: KeyResult
Dieses Feld habe ich nach Beispiel von @baeumelig mit einem Enum umgesetzt, welches definiert welche Einheit das Keyresult oder deren Measure hat (Percent, Text, Boolean)

- Feld: expected-evolution, Tabelle: KeyResult
Dieses Feld habe ich als int umgesetzt, sozusagen als vorausschauender Progress.

Was noch gemacht werden muss: 
Ich habe einen MergeRequest gestellt, der sollte von @tuxmatta oder @peggimann durchgesehen und überprüft werden.
