### ISSUE TITLE
OKR - Entity Objective

### ISSUE THREAD

**Issue by tuxmatta** [puzzle-bbt/bbt#254]
Entity **Objective** implementieren.

**Hinweise:**
- Das ERD-Diagramm findet ihr im CodeMD: https://codimd.puzzle.ch/VelTcGoRSRGyd8hFHpadjw#ERD-Diagramm
- Wir verwenden kein Lombok im Projekt.
- Für alle Entitäten werden Builder implementiert. Mit dem IntelliJ PlugIn `InnerBuilder` kann man Builder erstellen lassen.
- Alle Entitäten enthalten sinnvolle die hashCode(), equals() und toString() Methoden.
- Alle Entitäten enthalten sinnvolle Validation Constraints auf den Instanzvariablen wie Zum Beispiel: 
    `@NotNull`
    `@Size(min = 0, max = 150)`

**Comment by Vakmeth** [comment]
Vorgehen: 

- [x] Attribute den Anforderungen entnehmen und in Entity füllen
- [x] Nötige Methoden implementieren lassen (siehe Beschreibung)
- [x] Validators anfügen
