### ISSUE TITLE
OKR - Entity Team

### ISSUE THREAD

**Issue by tuxmatta** [puzzle-bbt/bbt#256]
Entity **Team** implementieren.

**Hinweise:**
- Das ERD-Diagramm findet ihr im CodeMD: https://codimd.puzzle.ch/VelTcGoRSRGyd8hFHpadjw#ERD-Diagramm
- Wir verwenden kein Lombok im Projekt.
- Für alle Entitäten werden Builder implementiert. Mit dem IntelliJ PlugIn `InnerBuilder` kann man Builder erstellen lassen.
- Alle Entitäten enthalten sinnvolle die hashCode(), equals() und toString() Methoden.
- Alle Entitäten enthalten sinnvolle Validation Constraints auf den Instanzvariablen wie Zum Beispiel: 
    `@NotNull`
    `@Size(min = 0, max = 150)`

**Comment by Vakmeth** [comment]
Erklärung: 

Da @kcinay055679 und ich nun das Repository bei mir hosten können, beginnen wir mit der Implementierung der Entity Objekte. Wenn das Repository soweit ist, stellen wir eine Anfrage an @tuxmatta um die nötigen Berechtigungen für einen Push zu erhalten.

Vorgehen: 
- [x] Attribute des ERDs von der Entity "Team" übernehmen
- [x] ToString(), hash() und equals() Methode implementieren
- [x] Builder Pattern einfügen
