### ISSUE TITLE
DB mit Testdaten

### ISSUE THREAD

**Issue by tuxmatta** [puzzle-bbt/bbt#261]
Als **Entwickler** möchte ich beim Starten der Applikation auf dem Entwicklungssystem eine Datenbank mit Testdaten haben, damit ich die Applikation direkt testen kann.

[Quick Guide on Loading Initial Data with Spring Boot](https://www.baeldung.com/spring-boot-data-sql-and-schema-sql)

#### Akzeptanzkriterien
* [x] Das DB-Schema soll beim Starten jeweils neu erstellt werden
* [x] Beim Start sollen in die leere Datenbank jeweils Testdaten aus einem SQL-Script File geladen werden.
* [x] Diese Funktion sollte ohne Java-Code umgesetzt werden

**Comment by njaeggi** [comment]
Automatisch starten funktioniert noch nicht, werde ich am Montagmorgen noch machen, die sql Statements stehen, werde die Pull Request erstellen sobald die keyresult und measure entity auf dem main sind, da ich diese brauche um die beiden sql statmements mit reinzunehmen, geschrieben udn getestet sind sie, jedoch noch auskommentiert.
