### ISSUE TITLE
Swagger UI hinzufügen

### ISSUE THREAD

**Issue by tuxmatta** [puzzle-bbt/bbt#262]
Als **Entwickler** möchte ich eine mit Swagger UI ein automatisch generierte Dokumentation und Testmöglichkeit der eigenen REST-Schnittstelle haben, damit ich Änderungen an der REST-Schnittstelle schneller Testen und den Frontend-Entwickler eine Dokumentation zur Verfügung stellen kann.

#### Akzeptanzkriterien
* [x] Swagger UI ist integriert und über das Web erreichbar: http://localhost:8080/swagger-ui/index.html
* [ ] Die bestehende REST-Schnittstelle ist mit Swagger Annotationen dokumentiert

**Comment by Vakmeth** [comment]
Ich habe das Swagger diesen Montag dem 01.11.22 mit dem Main rebased. Der MergeRequest wurde von @tuxmatta erstellt.
