### ISSUE TITLE
OKR Backend - neues Team erstellen

### ISSUE THREAD

**Issue by tuxmatta** [puzzle-bbt/bbt#265]
Als **Kunde** möchte ich beim Backend ein neues Team erstellen, damit ich im OKR-Tool mit einem neuen Team arbeiten kann.

Implementierung folgender Layer:
- Controller
- Service
- Repository
- DTOs (Data Transfer Objects)

REST-Schnittstelle:
```
POST /api/v1/teams
```

#### Akzeptanzkriterien
* [x] Die REST-Schnittstelle ist umgesetzt
* [x] Die Umsetzung ist mit jUnit-Tests getestet
* [x] Die REST-Schnittstelle ist mit SwaggerUI dokumentiert und getestet

**Comment by lkleisa** [comment]
Ich habe auf [einem Branch](https://github.com/puzzle/okr/tree/feature/265-create-team) folgende Sachen implementiert: 
- Rest aufruf mit RequestBody 
- Umwandlung von TeamDto in normales Team 
- Speicherung in db
- Neue Annotations für Validierung (klappte nicht nur mit @NotBlank -> Neue dependendcy spring boot starter validation, Entity @NotBlank und Column(nullable = false), TeamDto braucht auch noch @NotNull 
Jetzt kommt ein 400 zurück, wenn man kein Name angiebt und es wird kein leeres Team in DB gespeichert

Tests gibt es noch keine, diese würde ich am Freitag machen.
