### ISSUE TITLE
OKR Backend - Bestehendes Team ändern

### ISSUE THREAD

**Issue by tuxmatta** [puzzle-bbt/bbt#266]
Als **Kunde** möchte ich beim Backend ein bestehendes Team editieren, damit ich der Name eines Teams ändern kann.

Implementierung folgender Layer:
- Controller
- Service
- Repository
- DTOs (Data Transfer Objects)

REST-Schnittstelle:
```
PUT /api/v1/teams/42
```

#### Akzeptanzkriterien
* [x] Die REST-Schnittstelle ist umgesetzt
* [x] Die Umsetzung ist mit jUnit-Tests getestet
* [x] Die REST-Schnittstelle ist mit SwaggerUI dokumentiert und getestet

**Comment by Vakmeth** [comment]
Vorgehen: 
- [x] Zuerst in Teamcontroller Orientierung aufbauen, damit ich weiss wo was ist, dies auf main-branch
- [x] Danach branch "feature/team-aendern" erstellen
- [x] Schnittstelle für PUT nach Beispiel im Controller erstellen und commiten
- [x] Schnittstelle nach Beispiel testen, alle Tests nochmals ausführen und anschliessend commiten. 
- [x] Schnittstelle nach Besipiel dokumentieren, alle Tests nochmals ausführen und dann commiten. 
- [x] Wenn Feature Akzeptanzkriterien erfüllt, dann Pull Request stellen. Achten auf: Imports, Disabled Tests wieder aktivieren, Unnötiges weglöschen
