### ISSUE TITLE
OKR Backend - Liste der Objectives abrufen

### ISSUE THREAD

**Issue by tuxmatta** [puzzle-bbt/bbt#269]
Als **Kunde** möchte ich beim Backend die Liste der Objectives abrufen, damit ich eine Übersicht aller Objectives erhalte.

Implementierung folgender Layer analog dem TeamController und TeamService:
- Controller
- Service
- Repository
- DTOs (Data Transfer Objects)

REST-Schnittstelle:
```
GET /api/v1/objectives
```

#### Akzeptanzkriterien
* [x] Die REST-Schnittstelle ist umgesetzt
* [x] Die Umsetzung ist mit jUnit-Tests getestet
* [x] Die REST-Schnittstelle ist mit SwaggerUI dokumentiert und getestet

**Comment by Vakmeth** [comment]
Vorgehen: 

- [x] DTO nach Mockup umsetzten
- [x] Mapper für DTO und Entity implementieren
- [x] Repository für Objectives einfügen
- [x] Service implementieren, welcher Liste der Objectives zurückgibt.
- [x] Service mit Controller verknüpfen, hier Endpoint für GET auf die Objectives bauen, URL aus den Anforderungen verwenden.
- [x] Tests für den Controller, wie auch den Service schreiben.
- [x] Controller mit Swagger UI dokumentieren

**Comment by Vakmeth** [comment]
Die Ganze Rest-Schnittstelle ist dokumentiert, jedoch funktionieren die Annotationen noch nicht da die Swagger-Einbindung fehlt, welche auf einem anderen Branch gemacht werden soll.

Ebenfalls muss im ObjectiveMapper noch:
- [ ] TeamId welche auf 1 gesetzt ist duch objective.getTeam().getId() gewechselt werden, da die Setter in einem anderen Ticket festgehalten sind wird dieses Ticket auch von diesem blockiert.
- [ ] Das Gleiche muss bei der OwnerId gemacht werden.

Im ObjectiveMapperTest:
- [ ] Das Objective muss mit Builder komplett definiert werden und darf nicht einfach eine leere Instanz sein, hier wird ebenfalls noch auf das Ticket #279 gewartet damit auf diese Builder zugegriffen werden kann.

Übergeben habe ich das ganze Ticket gestern @kcinay055679
