### ISSUE TITLE
OKR Backend - neues Objectives erstellen

### ISSUE THREAD

**Issue by tuxmatta** [puzzle-bbt/bbt#271]
Als **Kunde** möchte ich beim Backend ein neues Objectives erstellen, damit ich im OKR-Tool mit einem neuen Objectives arbeiten kann.

Implementierung folgender Layer:
- Controller
- Service
- Repository
- DTOs (Data Transfer Objects)

REST-Schnittstelle:
```
POST /api/v1/objectives
```

#### Akzeptanzkriterien
* [x] Die REST-Schnittstelle ist umgesetzt
* [x] Die Umsetzung ist mit jUnit-Tests getestet
* [x] Die REST-Schnittstelle ist mit SwaggerUI dokumentiert und getestet

**Comment by lkleisa** [comment]
Ich musste einen neuen QuarterService erstellen, da man für das erstellen eines Objectives von der quarterId auf das Quarter Objekt kommen muss. Daher ist dieser in diesem Ticket erstellt. 
@MarcEgliP implementiert noch den Test für diesen QuarterService, der Rest ist gemacht, getestet und dokumentiert.

**Comment by Vakmeth** [comment]
Ich habe nun die Tests für den QuarterService fertig geschrieben. Ich werde nun den PullRequest, welcher bis jetzt als Draft gekennzeichnet war, richtig öffnen damit er reviewed werden kann.
