### ISSUE TITLE
OKR Backend - Bestehendes Objectives ändern

### ISSUE THREAD

**Issue by tuxmatta** [puzzle-bbt/bbt#272]
Als **Kunde** möchte ich beim Backend ein bestehendes Objectives editieren, damit ich das Objectives ändern kann.

Implementierung folgender Layer:
- Controller
- Service
- Repository
- DTOs (Data Transfer Objects)

REST-Schnittstelle:
```
PUT /api/v1/objectives/42
```

#### Akzeptanzkriterien
* [x] Die REST-Schnittstelle ist umgesetzt
* [x] Die Umsetzung ist mit jUnit-Tests getestet
* [x] Die REST-Schnittstelle ist mit SwaggerUI dokumentiert und getestet

**Comment by Vakmeth** [comment]
Vorgehen:

- [x] Zuerst in Teamcontroller Orientierung aufbauen, damit ich weiss wo was ist, dies auf main-branch
- [x] Danach branch "feature/objective-ändern" erstellen

- [x] Schnittstelle für PUT nach Beispiel im Controller erstellen und commiten

- [x] Schnittstelle nach Beispiel testen, alle Tests nochmals ausführen und anschliessend commiten.

- [x] Schnittstelle nach Beispiel dokumentieren, alle Tests nochmals ausführen und dann commiten.

- [x] Wenn Feature Akzeptanzkriterien erfüllt, dann Pull Request stellen. Achten auf: Imports, Disabled Tests wieder aktivieren, Unnötiges weglöschen

- [x] Auf Main Rebasen

**Comment by Vakmeth** [comment]
Bis Pullrequest gestellt werden kann, muss zuerst der Hauptbranch mit allen Controllern und Servicen in den Main gemerged werden, anschliessend kommt mein Branch als Ergänzung dazu. Der Hauptbranch wurde vom Ticket #271 aus gemacht.

**Comment by Vakmeth** [comment]
Der Hauptbranch von Lias wurde gemerged, somit werde ich nun vom Main rebasen und anschliessend einen Pullrequest stellen.
