### ISSUE TITLE
OKR Backend - Messung ändern

### ISSUE THREAD

**Issue by peggimann** [puzzle-bbt/bbt#277]
Als **Kunde** möchte ich beim Backend eine neue Messung abändern.

Implementierung folgender Layer:
- Controller
- Service
- Repository
- DTOs (Data Transfer Objects)

REST-Schnittstelle:
```
PUT  /api/v1/meassures/3
```

#### Akzeptanzkriterien
* [x] Die REST-Schnittstelle ist umgesetzt
* [x] Die Umsetzung ist mit jUnit-Tests getestet
* [x] Die REST-Schnittstelle ist mit SwaggerUI dokumentiert und getestet

**Comment by Vakmeth** [comment]
Vorgehen:

- [x] Main pullen und neuen branch "feature/277-messungen-ändern" generieren

- [x] Schnittstelle für PUT-Requests implementieren.

- [x] Schnittstelle (Service und Controller) testen

- [x] Controller mit SwaggerUI dokumentieren

- [x] Akzeptanzkriterien überprüfen, alle Files nochmals durchgehen, Imports optimieren, auf Main rebasen

- [x] PullRequest stellen
