### ISSUE TITLE
OKR Backend - Progress berechnen 

### ISSUE THREAD

**Issue by peggimann** [puzzle-bbt/bbt#280]
Bei new Meassure editieren, erstellen , löschen, soll der Progress jeweils neu berechnet werden auf dem Objective.... Ebenfalls bei löschen erstellen von Keyresult

- Neuer Service
- Async

**Comment by Vakmeth** [comment]
Vorgehen: 
- [x] Methode in neuem Service schreiben
- [x] Alle KeyResults aus DB holen und deren Measures für den Progress zusammenrechnen.
- [x] Progress in Prozent zurückgeben
- [x] Tests dafür schreiben
- [x] Imports optimieren und Pullrequest stellen

**Comment by tuxmatta** [comment]
Diese Umsetzung kann ich nicht annehmen: Funktional fehlerhaft und über die Performance möchte ich gar nicht sprechen! Ich öffne die Story und wir versuchen es nochmals.

**Comment by Vakmeth** [comment]
Ist blockiert solange das Ticket #299 nicht in den Main gemerged wird, da @njaeggi auf diesem Branch ein Query für die neue Implementation des Progress berechnen bereitgestellt hat.

**Comment by Vakmeth** [comment]
Ticket #299 von @njaeggi wurde gemerged, somit kann mit diesem Ticket nochmals begonnen werden.

**Comment by Vakmeth** [comment]
Der Progress wird nun per Query berechnet, allerdings bin ich mir bei der Implementation der Integrationstests noch unsicher, welche ich mit @tuxmatta am Montag noch besprechen werde. Deswegen, Ticket bis dahin nicht übernehmen.
