### ISSUE TITLE
OKR Backend - Testabdeckung messen

### ISSUE THREAD

**Issue by tuxmatta** [puzzle-bbt/bbt#284]
Als **Entwickler** möchte ich die Testabdeckung messen, damit man eine Übersicht des getesteten Programmcode erhält.

Dafür kann das Maven Plugin **JaCoCo wie im Projekt migration-wekan-taiga** verwendet werden.
https://www.baeldung.com/jacoco

Es sollen die folgenden drei Metriker gemessen werden:
* Lines coverage
* Branches coverage
* Cyclomatic complexity 

Untersuchen, ob die Integrationstests auch von JaCoCo gemessen werden.

#### Akzeptanzkriterien
* [x] Die Messung der Testabdeckung wird mit Maven ausgeführt.
* [x] Es sind für alle drei Metriken sinnvolle Grenzwerte gesetzt.
* [x] Beim Ausführen von mvn package soll die Testabdeckung gemessen werden.

**Comment by kcinay055679** [comment]
Die Dateien werden noch nicht excluded.
Das Exclude Tag befindet sich noch an der falschen Stelle.
Siehe [Dokumentation](https://www.baeldung.com/jacoco-report-exclude)

**Comment by tuxmatta** [comment]
Resultat Seite von JaCoCo: backend/target/site/jacoco/index.html
