### ISSUE TITLE
ORK Backend - Gute SwaggerUI Doku

### ISSUE THREAD

**Issue by tuxmatta** [puzzle-bbt/bbt#286]
Als **Entwickler** möchte ich eine gute SwaggerUI Doku, damit ich bei der Fehlersuche die nötigen Infos rasch erhalte.

Die SwaggerUI Doku hat noch Schwäche, welche man verbessern kann. Sieht in der swagger.io Dokumentation nach, was alles Möglich ist. Es existiert auch ein Npm Paket swagger-editor. Eventuell wäre dies eine Hilfe.

#### Akzeptanzkriterien
* [x] Überall werden die  DT0's statt den Entitäten verwendet.
* [x] Alle Argumente sind beschrieben.
* [x] Alle sinnvollen Möglichkeiten zur Beschreibung REST-Schnittstelle sind genützt.
* [x] Die Dokumentation ist aussagekräftig und aus einem Guss (gleicher Style bei der Beschreibung der verschiedenen Aufrufe).
* [x] Die Dokumentation (http://localhost:8080/swagger-ui/index.html) wurde manuell gut getestet. Alle Aufrufen und fehlerhafte Aufrufe wurden manuell durchgeführt.

**Comment by lkleisa** [comment]
Swagger doc wurde angepasst und überall gleich gemacht. So ist es übersichtlicher.
Wenn man ein Objective updaten oder createn will, bspw. auf http://localhost:8080/swagger-ui/index.html#/objective-controller/updateObjective updatet, kommt ein Fehler, dass die owner id fehlt. Ich weiss nicht, wieso das so ist, sollte aber nicht an swagger liegen. Der Rest geht alles.
