### ISSUE TITLE
OKR Frontend - Vorbereitung zur Angular Komponenten-Aufteilung

### ISSUE THREAD

**Issue by tuxmatta** [puzzle-bbt/bbt#287]
Als **Entwickler** möchte ich einen Vorschlag zur Aufteilung des Frontend in Angular Komponente machen, damit wir im Planning auf diesem Vorschlag aufbauen können.

- Nach welchen Kriterien sollte man die Aufteilung vornehmen, was muss man berücksichtien?
- Kann man einzelne Komponenten mehrfach verwenden?
- Wie ist der Datenfluss zwischen den Komponenten und wie/wer lädt über die REST-Schnittstelle Daten vom Backend?

**Tipp**
- Druckt einzelne Seiten aus dem Figma aus und markiert in einem ersten Schritt die Ansichten der einzelnen Komponenten.
- Überleg euch in einem zweiten Schritt, wie die Komponenten zu den Daten gelangen und wie sie allenfalls Daten oder Events weitergeben.
- [Components im Frontend](https://codimd.puzzle.ch/45mmO4FFQiWJX20dwJMDlw)

#### Akzeptanzkriterien
* [x] Kriterien für die Aufteilung sind definiert
* [x] Die Aufteilung ist dokumentiert und es existiert eine Liste aller Komponenten.
* [x] Der Datenfluss von der REST-Schnittstelle zu den einzelnen Komponenten und zwischen den Komponenten ist dokumentiert.

**Comment by njaeggi** [comment]
Grobe Übersicht eingezeichnet und aufgeschrieben, auch Überlegung über den Datenfluss gemacht, werde dies am Montag bis zum Review abschliessen
