### ISSUE TITLE
OKR Backend - Über die REST-Schnittstelle werden nur DTO's ausgetauscht

### ISSUE THREAD

**Issue by tuxmatta** [puzzle-bbt/bbt#289]
Als **Entwickler** möchte ich dass über die REST-Schnittstelle werden nur DTO's ausgetauscht werden, um die Entity Objekte der Persistenz-Schicht und das Frontend zu Entkoppeln.

#### Akzeptanzkriterien
* [x] Über die REST-Schnittstelle werden nur DTO's ausgetauscht.

**Comment by Vakmeth** [comment]
Vorgehen: 
- [x] Anstatt Entities bei PUT und POST Requests das DTO zurückgeben, hierzu zurückgegebene Entities mit Mapper zu DTO Mappen
- [x] Tests überprüfen, Imports optimieren
- [x] Pullrequest stellen

**Comment by tuxmatta** [comment]
Wieso wurden in den Controllern folgende Änderungen umgesetzt? Was ist der Vorteil? Falls keinen, die Änderung rückgängig mache.

vorher:
```
public ObjectiveDto getObjective(
...
return objectiveMapper.toDto(objectiveService.getObjective(id));
```
nachher:
```
public ResponseEntity<ObjectiveDto> getObjective(
...
return ResponseEntity.status(HttpStatus.OK).body(this.objectiveMapper.toDto(objectiveService.getObjective(id)));
```

**Comment by Vakmeth** [comment]
Vorteile der Verwendung von ResponseEntity: 

- Volle Kontrolle über die HttpResponse
- Header kann angepasst werden, falls dies irgendwann in der Weiterentwicklung gewünscht ist
- Status Code kann angepasst werden (Sehr nützlich wenn man bei POST 201 anstatt 200 zurückgeben will)

Nachteile der Nichtverwendung:
- Spring generiert die HttpResponse automatisch, ohne das wir Kontrolle über diese haben (Ausgenommen dem Body).

Alles in allem, haben wir mit der Verwendung der ResponseEntity mehr Kontrolle über den Rückgabewert und können so bei späteren Anpassungen diese leichter umsetzten.
