### ISSUE TITLE
OKR - Anmeldung über SSO abklären

### ISSUE THREAD

**Issue by tuxmatta** [puzzle-bbt/bbt#290]
Als **Puzzle Member** möchte ich mich mit dem SSO von Puzzle anmelden können, damit ich das OKR-Tool verwenden kann.

Für die Authentisierung, Autorisierung und das Single Sign-on soll der Puzzle Dienst **Keycloak** (sso.puzzle.ch) verwendet werden. Als Protokoll ist aktuell **OAuth 2.0** vorgesehen. Sollte es sich zeigen, dass sich OpenIDconnect oder SAMLv2 besser eignen, können auch diese Protokolle eingesetzt werden.

**Fragestellungen:**
- Wie kann man sich über SSO anmelden?
- Wie kann der neu angemeldete User in die Datenbank vom OKR-Tool übernommen werden?
- Wie sieht der Ablauf aus?
- Wie kann man sicherstellen, dass nur Puzzle Members zugriff auf das OKR-Tool erhalten?
- Wie kann man in Zukunft verschiedene Benutzergruppen mit unterschiedlichen Rollen einführen?
- Was muss auf dem Backend umgesetzt werden?
- Was muss auf dem Frontend umgesetzt werden?
- Wer kann uns bei der Umsetzung unterstützten?

**Infos:**
- [SSO / Keycloak User Guide](https://docs.puzzle.ch/user-guides/keycloak-user-guide/index.html)

#### Akzeptanzkriterien
* [ ] Alle Fragen sind beantwortet und in diesem Ticket abgelegt.

**Comment by baeumelig** [comment]
Wie kann man sich über SSO anmelden?:
Mit den Puzzle Credentials

Wie kann der neu angemeldete User in die Datenbank vom OKR-Tool übernommen werden?
In dem man den angemeldeten User(Token) mit der Datenbank abgleicht und falls dieser nicht existiert wird er neu erstellt. Im Token sind alle relevanten Daten

Wie sieht der Ablauf aus?

Wie kann man sicherstellen, dass nur Puzzle Members zugriff auf das OKR-Tool erhalten?
In dem man das Puzzle SSO verwendet.  

Wie kann man in Zukunft verschiedene Benutzergruppen mit unterschiedlichen Rollen einführen?
Momentan hat das OKR-Tool nur eine Rolle: User
Diese kann auch aus dem Token gelesen werden und ist garantiert da nur Puzzle Members sich anmelden können.

Wie kann man in Zukunft verschiedene Benutzergruppen mit unterschiedlichen Rollen einführen?
Neue Rollen kann man auf dem KeyCloak Realm erstellen, diese werden dann im Token mitgegeben

Was muss auf dem Backend umgesetzt werden?
Backend (bearer-only) Client

Was muss auf dem Frontend umgesetzt werden?
Frontend (hybrid) Client

Wer kann uns bei der Umsetzung unterstützten?
Etienne Gobeli oder Ramon Spahr. Jenachdem auch Stephan Girod
Ein Problem hier könnte die Zeit und Verrechenbarkeit sein
