### ISSUE TITLE
OKR Frontend - Programmcode automatisch formatieren

### ISSUE THREAD

**Issue by tuxmatta** [puzzle-bbt/bbt#291]
Als **Entwickler** möchten wir unseren Programmcode einheitlich formatieren, damit wir die durchgeführten Änderungen besser erkennen und einfacher Mergen können.

* Als Code Formatter möchten wir im Frontend den [Prettier](https://prettier.io/) einbauen.
* [Puzzle Prettier User Guide](https://docs.puzzle.ch/user-guides/prettier-user-guide/index.html)

#### Akzeptanzkriterien
* [x] Der Code Formatter formatiert der Programmcode beim Kompilieren.
* [x] Der Code Formatter kann das Format des Programmcode validieren und den Build fehlschlagen lassen. Zum Beispiel in Build Pipeline der GitHub Action.
* [x] Der aktuell existierende Programmcode ist vollständig formatiert.

**Comment by lkleisa** [comment]
Ich habe prettier zu unserem okr frontend hinzugefügt. 
- Man muss einmal nach git pull `npm run prestart` ausführen, damit man im lokalen .git ordner ein pre-commit script hat
- Man kann mit `npm run format` den Code formatieren lassen
- Man kann mit `npm run check` den Code überprüfen lassen
- Wenn man commited wird der Code überprüft und bei unformatiertem Code wird der Commit abgebrochen
- Wenn man pusht, läuft neben dem build noch eine prettier action durch, welche bei nicht formatiertem Code den build fehlschlagen lässt

**Comment by lkleisa** [comment]
Der PR ist offen, es muss aber dringend das create angular zuerst gemerged werden!
