### ISSUE TITLE
OKR Frontend - Angular Frontend erstellen

### ISSUE THREAD

**Issue by tuxmatta** [puzzle-bbt/bbt#294]
Als **Entwickler** möchten wir ein Angular Frontend erstellen, welches wir als Frontend zum OKR-Backend verwenden möchten.

**Weiter Infos:**
* [Lernziel: Angular : 2. Angular Frontend bauen](https://codimd.puzzle.ch/mvV7omfwQvCqrX5AQzdfzw#2-Angular-Frontend-bauen)

#### Akzeptanzkriterien
- [x] Das leeres Angular Frontend mit einer statischen Startseite ist erstellt und kann gestartet werden.
- [x] Das Frontend kann gebildet werden.

**Comment by Vakmeth** [comment]
Vorgehen: 
- [ ] Neues Modul für das Frontend anlegen
- [ ] Frontend Applikation starten
- [ ] Wenn startbar, Draftpullrequest stellen und übergeben
