### ISSUE TITLE
OKR Frontend - Testing: Jest statt Karma verwenden

### ISSUE THREAD

**Issue by tuxmatta** [puzzle-bbt/bbt#295]
Als **Entwickler** möchten wir Jest statt Karma verwenden, damit wir stabilere und schnellere Tests erhalten.

**Gründe für den Wechsel:**
* Parallel testing: Jest, by default, runs tests in parallel, to minimize the time it takes to execute tests.
* Jest does not need any browser to load the test in the browser and execute it.
* Sandboxing: Jest sandboxes all tests to prevent global variables or state from a previous test to affect the results of the next one, and
* Code coverage reports: with Karma and Jasmine, you have to set up a plugin for code coverage. Adding TypeScript into the mix makes things even more difficult to process. By contrast, Jest will provide code coverage reports out of the box.

**Weitere Infos:**
- [Integrate Jest into an Angular application and library](https://timdeschryver.dev/blog/integrate-jest-into-an-angular-application-and-library#creating-an-angular-application)
- Mit Jest kann man die Jasmine Tests auch ausführen.

#### Akzeptanzkriterien
* [x] Jest ist integriert und `npm test` startet die Jest zur Testausführung.
* [x] Es ist dokumentiert, wie man im IntelliJ die Jest Tests ausführen kann.
* [x] Karma ist ausgebaut.
* [x] Ein exemplarischer Jest Test Test ist implementiert.
* [x] Ein exemplarischer Jasmine Test ist implementiert.

**Comment by njaeggi** [comment]
Das umstellen auf Jest hat funktioniert, die bestehenden Tests wurden von der karma 'it' Bezeichnung auf 'test' von jest umgeschrieben. Karma wurde vollständig ausgebaut.

Noch offen:
- Tests können bisher nur auf Konsole ausgeführt werden
- Exemplare sollten vorhanden sein, noch nicht klar wie gut die Exemplare sind
