### ISSUE TITLE
OKR - Deploy über GitHub Actions Pipeline

### ISSUE THREAD

**Issue by tuxmatta** [puzzle-bbt/bbt#298]
Als **Entwickler** möchte ich das OKR-Tool auf dem OpenShift von Puzzle deployen, da dies der empfohlene Ort zum Betreiben von Puzzle Diensten ist.

Wir verwenden eine zweite GitHub Actions Pipeline zum Builden, Testen und Deployen des ORK-Tools, ähnlich wie beim Puzzle ScrumPoker. Jedoch verwenden wir für die Produktion den Branch **production**.

Folgende geschützte Branchs existierten aktuell:
- **main** : Ist die aktuelle Entwicklerversion
- **production**: Ist die produktive Version

#### Akzeptanzkriterien
* [x] Der Deploy des OKR-Tool wird durch einen Push auf den Branch **production** ausgelöst.
* [x] Nach einem erfolgreichen Deploy ist die neue Version auf dem OpenShift verfügbar.

**Comment by kcinay055679** [comment]
Die Pipeline für das automatische hochladen in das [quay Repository](https://registry.puzzle.ch/repository/puzzle/okr)  ist auf dem Branch feature/289-deploy erstellt.
Jedoch gibt es nocht ein Problem mit den Berechtigungen welches verhindert das ein Image via GIt Actions in das Repo hochgeladen wird.


Ein entsprechendes Openshift Projekt habe ich bereits erstellt. Die Infrastruktur dafür habe ich in folgendem [Repo](https://github.com/puzzle/okr-infra) abgelegt. 
Das Openshift Projekt ist unter folgender Url zu finden: [OpenShift](https://openshift.cloudscale.puzzle.ch/k8s/cluster/projects/pitc-okr)
Im Openshift laufen 3 Pods: Der Datenbank Pod, und 2 Backendpods. Der Datenbankpod sieht soweit funktionstüchtig aus. Die Backendpods haben das Problem das diese entweder das Dockerimage gar nicht abrufen können, oder das die Applikation innerhalb des Images einen Fehler wirft.

**Comment by kcinay055679** [comment]
Ich habe auf Anfrage von Christian Haller ein neues OpenShift Projekt erstellt und die richtigen Lables gesetzt.
Zurzeit funktioniert weder das automatische pushen des Image auf [registry.puzzle.ch](registry.puzzle.ch) noch funktionieren laufen die Pods welche im Openshift generiert werden.

**Comment by kcinay055679** [comment]
Ich habe ein zweites Quayrepo erstellt jedoch bin ich, "yminder" und nicht "Puzzle" als Owner eingetragen.
Dadurch hatte ich die Möglichkeit einen Roboaccount zu erstellen der von Github verwendet wird um automatisch auf das neue Repo zu pushen.

**Comment by kcinay055679** [comment]
Neues [Quay Repo](https://registry.puzzle.ch/repository/yminder/puzzle-okr)
Neues [Openshift Projekt](https://openshift.cloudscale.puzzle.ch/k8s/cluster/projects/pitc-okr-prod)
Das Backend kann jetzt unter folgener Adresse aufgerufen werden: 
[http://backend-pitc-okr-prod.ocp-internal.cloudscale.puzzle.ch](http://backend-pitc-okr-prod.ocp-internal.cloudscale.puzzle.ch)
Dabei ist es wichtig das "http" verwendet wird und nicht "https"

**Comment by kcinay055679** [comment]
Openshift reagiert jetzt automatisch auf ein neues Image in dem ein Imagestream in einem 15 Minuten Intervall prüft ob ein neues Images existiert und wenn ja einen neuen Pod mit diesem startet
