### ISSUE TITLE
OKR - Backend Liste der Keyresults soll letzte Messung beinhalten

### ISSUE THREAD

**Issue by peggimann** [puzzle-bbt/bbt#299]
Als **Kunde** möchte ich beim Backend eine Liste aller Keyresults, zu den jeweiligen Objectives, inklusive den Messungen hinzufügen.

Implementierung folgender Layer:
- Controller, GET Mapping anpassen
- Service
- DTOs (Data Transfer Objects), neues DTO, KeyresultMessung...

REST-Schnittstelle:
```
GET /api/v1/objectives/12/keyresults     // letzte Messung ist dabei
```

#### Akzeptanzkriterien
* [x] Die REST-Schnittstelle ist umgesetzt
* [ ] Die Umsetzung ist mit jUnit-Tests getestet
* [x] Die REST-Schnittstelle ist mit SwaggerUI dokumentiert und getestet

**Comment by njaeggi** [comment]
Noch offen:
Wenn das KeyResult kein Measure hat, gibt es noch einen Fehler, es sollte das KeyResult returnen mit measure auf null gesetzt. Normale Abfrag funktioniert, Tests fehlen auch noch

**Comment by njaeggi** [comment]
Werde dies am Donnerstag abschliessen
