### ISSUE TITLE
OKR Frontend - Kopfzeile und eine Navigationsleiste im PuzzleShell Style

### ISSUE THREAD

**Issue by tuxmatta** [puzzle-bbt/bbt#300]
Als **Kunde** möchte ich eine Kopfzeile und eine Navigationsleiste sehen, damit ich mich durch das Tool navigieren kann.

- Für alle Komponenten gilt die Puzzle standard Styles (PuzzleShell) und es werden die Angular Material UI Widgets/Componenten verwendet.
- Das Logo `OKR` habe ich bei Mathis bestellt.
- Die User-Information auf der rechten Seite kann man weglassen.
- Wir implementieren aktuell nur das Menu **OKRs** mit den beiden Unterpunkten: **Overview** und **Team**. Es sind nur `console.log('...')` Actions hinterlegt.

![Screenshot from 2022-11-14 17-44-44.png](https://images.zenhubusercontent.com/61641bda09cd979ad092c0cb/2f2e8d47-ce08-4625-9800-c71e2316e26e)

#### Akzeptanzkriterien
* [x] Die Ausgabe entspricht dem ScreenShot 
* [x] Angular Komponente und das Template sind mit Jest getestet (aktuell Karma)
* [x] Die benötigten Daten werden mittels Service + RxJS gelade

**Comment by lkleisa** [comment]
Ich habe auf dem branch feature/300-puzzleshell mit der Shell einbindung begonnen. 
- Die Top bar existiert
- Das Menu unten auch (ist auch von der Puzzle shell)
- Angular Material ist hinzugefügt
- Beim klicken des Menus wird ein console.log() ausgeführt 

1) Tests stehen noch keine
2) Es werden auch keine Daten geladen

**Comment by peggimann** [comment]
- Logo wurde gewechselt auf Puzzle Okr
- KPI sollte entfernt werden 
- Logos und Buttons im Header aneinander anpassen
- Tests müssen noch erstellt werden
