### ISSUE TITLE
OKR Frontend - Dashboard mit 2 Filter

### ISSUE THREAD

**Issue by tuxmatta** [puzzle-bbt/bbt#301]
Als **Kunde** möchte ich zwei Filter auf dem Dashboard, damit ich die Objectives nach Teams und Quartal filtern kann.

- Der Button *Ziel erstellen* gehört nicht zum Inhalt.
- Die Daten für den Team-Filter werden über einen neuen Service geladen: `api/v1/teams`
- Die Daten für den Quartals-Filter (Zyklus) werden im Frontend generiert: aktuelles Quartal + vier Quartale zurück + ein Quartal in die Zukunft

![Dashboard mit 2 Filter.png](https://images.zenhubusercontent.com/61641bda09cd979ad092c0cb/779965c4-d690-4e67-ae32-803b193d4d6f)

#### Akzeptanzkriterien
* [x] Die Ausgabe entspricht dem ScreenShot 
* [ ] Angular Komponente und das Template sind mit Jest getestet
* [x] Die benötigten Daten werden mittels Service + RxJS geladen.

**Comment by lkleisa** [comment]
Die Teams werden vom Backend geholt und in das Angular Material Multiple Select Drowpdown geladen. Die Zyklen werden automatisch generiert und man kann einen auswählen. 
Tests müssen noch geschrieben werden, @tuxmatta stellt zuerst noch Beispieltests zur Verfügung.
