### ISSUE TITLE
OKR Frontend - Team Detail

### ISSUE THREAD

**Issue by tuxmatta** [puzzle-bbt/bbt#302]
Als **Kunde** möchte ich zu jedem Team die zugehörigen Objectives auf dem Dashboard angezeigt haben, damit ich auf einen Blick sehe, welches Team welche Objectives zugewiesen hat. 

- Das Template zeigt für jedes Team alle zugehörigen Objectives an. 
- Die ansicht der einzelnen Objectives gehört nicht zu der Komponente.
- Die Daten für die Team- Objectives werden über einen neuen Service geladen: `api/v1/teams/{id}/objectives`
- Die Daten für  die Team- Objectives werden in der Parent Komponente geladen
- In der Parent Komponente wird zusätzlich ein `ngFor` verwendet um alle Teams anzuzeigen

![Screenshot from 2022-11-14 17-28-31.png](https://images.zenhubusercontent.com/6324625e883a4fc071be1145/65939674-5d1f-4f78-a9c7-fb58719f6e8a)

#### Akzeptanzkriterien
* [x] Die Ausgabe entspricht dem ScreenShot 
* [x] Angular Komponente und das Template sind mit Jest getestet
* [x] Die benötigten Daten werden mittels Service + RxJS geladen.

**Comment by Vakmeth** [comment]
Vorgehen: 
Da im Moment der Dashboard Component noch nicht in den Main-Branch gemerged wurde, werde ich die Daten für den Team-Detail Component manuell bereitstellen und danach zuerst das Template für den Component bauen:

- [x] Neuen Component "team-detail" generieren
- [x] Daten manuell in ts File übergeben
- [x] Template mit Angular Material nach Bild (siehe oben) realisieren.
- [x] Daten per Service einbinden
- [x] Sobald #301 gemerged, rebasen und Component auf dieses Muster anpassen.
- [x] Tests schreiben

**Comment by MarcEgliP** [comment]
Momentan werden die Daten noch manuell eingetragen, solange @lkleisa noch die Tests schreibt, werde ich auf seinen Branch rebasen und die Daten per Service holen gehen.

**Comment by MarcEgliP** [comment]
Momentan ist das Ticket geblocked, da wir alle Objectives eines Teams abrufen müssen und dazu die REST-Schnittstelle noch nicht steht.

**Comment by Vakmeth** [comment]
Momentan fehlt die REST-Schnittstelle, welche bei #309 implementiert werden sollte. Durch die Blockade, kann der neue hinzugefügte ObjectiveService auch noch nicht getestet werden.

**Comment by Vakmeth** [comment]
Was nach Implementation der REST-Schnittstelle gemacht werden muss:

- [x] Div mit ngfor in team-details.component.html auskommentieren
- [x] ObjectiveService testen, der Component selbst wurde schon getestet hier sind keine weiteren Tests nötig
- [ ] Pullrequest stellen

**Comment by lkleisa** [comment]
Ich habe die Logik ein wenig verändert, da sie funktional nicht ganz richtig war. Jetzt funktioniert alles so wie es soll und wurde auch getestet. Der Branch ist schon von 309 gebrebased worden, jetzt müssen wir warten, bis dieser im main ist: 
- [ ] Wenn 309 im main ist von main rebasen
- [ ] Funktionen im Frontend und tests überprüfen
- [ ] PR stellen
