### ISSUE TITLE
OKR Frontend - Objective Row

### ISSUE THREAD

**Issue by tuxmatta** [puzzle-bbt/bbt#303]
Als **Kunde** möchte ich die Objectives eines Teams anzeigen, damit ich eine Übersicht der Objectives eines Teams habe.

- Die Objective Row Komponente stellt ein Objective dar.
- Oberhalb des Objectives ist eine horizontale Linie.
- Die Daten für diese Komponente werden als Input-Parameter gesetzt.
- Der Progress wird mit einem Datenbalken und einer Prozentzahl angezeigt.

![Screenshot from 2022-11-14 17-28-51.png](https://images.zenhubusercontent.com/61641bda09cd979ad092c0cb/a7b40738-5ac4-4283-be0a-db0e57fbc9ab)

- Die Komponente kann sich aufklappen um eine weitere Kind-Komponente anzuzeigen.
- Sie besitzt auf der rechten Seite ein Menu mit vier Einträgen. Das Menu soll angezeigt werden, aber es sind nur `console.log('...')` Actions hinterlegt.
![Screenshot from 2022-11-14 17-35-57.png](https://images.zenhubusercontent.com/61641bda09cd979ad092c0cb/bdbbcb14-b32f-4bb3-ae8d-2e1b8c807869)

#### Akzeptanzkriterien
* [x] Die Ausgabe entspricht dem ScreenShot 
* [ ] Angular Komponente und das Template sind mit Jest getestet
* [x] Die benötigten Daten werden mittels Service + RxJS geladen.

**Comment by Vakmeth** [comment]
Ticket ist geblockt, da momentan die REST-Schnittstelle dafür noch nicht besteht.

**Comment by Vakmeth** [comment]
Was nach Implementation der blockierenden REST-Schnittstelle gemacht werden muss: 
- [x] Div mit ngfor im team-detail.component.html auskommentieren.
- [ ] Komponent testen
- [ ] Warten bis #302 gemerged wurde, rebasen und Pullrequest stellen.

**Comment by lkleisa** [comment]
Ich habe die Logik von 302 Team Detail hier übernommen, die Objetive row stimmt jetzt so und wird richtig angezeigt. Wenn der Branch 309 und 302 gemerged wurden, kann dieser von main gebrebased werden. 
- [ ] Tests schreiben
- [ ] Rebasen
- [ ] PR stellen

**Comment by lkleisa** [comment]
Ich habe mit dem Schreiben der Tests für den objective-row.component begonnen. Es müssen aber noch mehr, z.B. für das mat-menu geschrieben werden

**Comment by lkleisa** [comment]
Es fehlt noch ein Test für das mat-menu in der objective row. Ich konnte per querySelector nicht darauf zugreifen und somit nicht die Elemente überprüfen.
