### ISSUE TITLE
OKR Frontend - Objective (Ziel) Detail

### ISSUE THREAD

**Issue by tuxmatta** [puzzle-bbt/bbt#304]
Als **Kunde** möchte ich ein Objective ausklappen, damit ich sehen kann, welche Keyresults darauf einzahlen und wie der Fortschrit auf diesen ist.

- Das Menü gehört nicht zum inhalt.
- Die Daten für die Keyresults pro Objective werden über einen neuen Service nachgeladen:
 `/api/v1/objectives/{id}/keyresults`
- Die Komponente zeigt mittels `ngFor` alle Keyresult Rows zu dem Objective an. 
- Die Komponente zeigt zusätzliche Informationen zu dem Objective an, welchem Quartal dieses Zugeordnet ist und wer Besitzer des Objectives ist. 

![Objective Detail.png](https://images.zenhubusercontent.com/6324625e883a4fc071be1145/472ab6c1-73b5-43e0-b9ed-3fd157497c5d)

#### Akzeptanzkriterien
* [x] Die Ausgabe entspricht dem ScreenShot 
* [ ] Angular Komponente und das Template sind mit Jest getestet
* [x] Die benötigten Daten werden mittels Service + RxJS geladen.

**Comment by Vakmeth** [comment]
Vorgehen: 
- [x] Neue Komponente erstellen "objective-detail".
- [x] Komponent nach Vorgabe des Mockups erstellen.
- [x] Service einbauen
- [ ] Komponent testen
- [ ] Code Optimierung und Formattierung + Pullrequest stellen

**Comment by Vakmeth** [comment]
Komponent kann nicht getestet werden, solange der Pullrequest von #295 noch nicht gemerged wird.

**Comment by Vakmeth** [comment]
Das Ticket #295 wurde gemerged, nun können Tests geschrieben werden.

**Comment by Vakmeth** [comment]
Was noch gemacht werden muss: 
- [ ] HTML Komponent und key-result Service testen.
- [ ] Im Moment ist der objective detail-component noch im objective-row html abgelegt. Sobald der Pullrequest von #305 gemerged wurde, muss von diesem Branch gerebased werden und der Komponent kann in diese Row verschoben werden. Um dies zu erreichen muss zwischen den row component tags von #305 unser Komponent eingefügt werden.
- [ ] Danach kann der Pullrequest gestellt werden
