### ISSUE TITLE
OKR Frontend - KeyResult (Resultat) Overview

### ISSUE THREAD

**Issue by tuxmatta** [puzzle-bbt/bbt#306]
Als **Kunde** möchte ich ein Keyresult ausklappen, damit ich sehen kann, welche spezifizierungen zum Keyresult noch zusätzlich zum Titel gemacht wurden und welche Einzelheiten die letzte Messung beinhaltet .

- Das Menü gehört nicht zum inhalt.
- Die Daten für die Keyresult-Overview wurden bereits im Objectiv-Detail geladen
- Die Komponente ist Ausklapbar und zeigt alle infos zum Keyresult an. 

![Keyresult Overview.png](https://images.zenhubusercontent.com/6324625e883a4fc071be1145/78c9d067-73c3-455b-ba41-c57edcbcd4d8)

#### Akzeptanzkriterien
* [ ] Die Ausgabe entspricht dem ScreenShot 
* [ ] Angular Komponente und das Template sind mit Jest getestet
* [ ] Die benötigten Daten werden mittels Service + RxJS geladen.

**Comment by Vakmeth** [comment]
Vorgehen: 
- [x] Neuen Komponent machen "keyresult-detail"
- [x] Komponent nach vorgegebenen Screenshot aufbauen
- [x] Alle Daten per @Input in gemachte Komponente übergeben
- [ ] Komponent testen
- [ ] Code optimieren, Pullrequest stellen

**Comment by Vakmeth** [comment]
Was noch gemacht werden muss:
- [ ] Im Objective detail Komponent wurden TODOs zur Hilfestellung erfasst.
- [ ] Dieser Komponent muss noch getestet werden
- [ ] Ebenfalls gilt es den Keyresult Detail Komponent wie bei #304 zwischen die Row-Tags zu setzten und danach das Frontend zu überprüfen.
- [ ] Dies kann erst gemacht werden wenn #304  und #305 gemerged sind.
