### ISSUE TITLE
OKR Frontend - Team Liste

### ISSUE THREAD

**Issue by tuxmatta** [puzzle-bbt/bbt#307]
Als **Kunde** möchte ich eine Liste von allen Teams der Organisation anzeigen, damit ich immer weiss, welche Teams der Organisation angehören.
 
- Die Daten für die Teams werden über einen neuen Service geladen: `api/v1/teams`
- Der Button Team erstellen gehört nicht zu dieser Story. 

![TeamListe.png](https://images.zenhubusercontent.com/6324625e883a4fc071be1145/6285415f-0839-4e51-ab19-d09a6d65ed20)

#### Akzeptanzkriterien
* [x] Die Ausgabe entspricht dem ScreenShot 
* [x] Angular Komponente und das Template sind mit Jest getestet
* [x] Die benötigten Daten werden mittels Service + RxJS geladen.

**Comment by lkleisa** [comment]
Die Liste wird auf /teams korrekt angezeigt und sieht so aus wie auf dem Screenshot. Tests sind geschrieben und funktionieren.
Es gibt noch ein Fehler im Puzzle Shell Menu, man kann nicht auf /teams navigieren. @baeumelig hat sich an das gesetzt und mit Mathis Hofer geschaut, sie schauen nächsten Montag zusammen.
