### ISSUE TITLE
OKR Frontend - Team Erstellen und Edit

### ISSUE THREAD

**Issue by tuxmatta** [puzzle-bbt/bbt#308]
Als **Kunde** möchte ich neue Teams erstellen, sowie auch bearbeiten können, damit die Teamliste im Tool immer der aktuellen Team Struktur der Organisation entspricht.

* Die Daten für das neue erstellen eines Teams und bearbeiten eines Teams, verwenden den Service: `api/v1/teams/:id`
* Der Pfad im Frontend ist:
  * `/team/edit`
  * `/team/edit/42`

![create_team.png](https://images.zenhubusercontent.com/6324625e883a4fc071be1145/570d0439-4b58-4bc9-bd39-36961a0f092d)
![edit_team.png](https://images.zenhubusercontent.com/6324625e883a4fc071be1145/af7928ba-c595-49b3-b03b-542f3c878988)

#### Akzeptanzkriterien
* [x] Die Ausgabe entspricht dem ScreenShot 
* [ ] Die Knöpfe Erstellenund Speichern sind erst aktive, wenn das Formular valid ist und es gibt eine Validierung für den Namen.
* [ ] Angular Komponente und das Template sind mit Jest getestet
* [x] Die benötigten Daten werden mittels Service + RxJS geladen.

**Comment by lkleisa** [comment]
Zuerst braucht man #307 team liste.
Man kann entweder ein Team erstellen (über den Button in der TeamList) oder eines bearbeiten (über den edit button in der TeamList). 
Es gibt noch einen Fehler, dass das Angular über 4200/api/v1/teams gehen will und nicht auf das Backend. Dies konnte ich noch nicht beheben. 
Das update funktioniert schon mit dem backend. Das create hat noch ein Fehler, welcher ich noch nicht gefunden habe.
Das Formular wird validiert und bei leerem Namen ist der button disabled.
Tests müssen noch geschrieben werden.
