### ISSUE TITLE
OKR Frontend - KeyResult (Resultat) erstellen + bearbeiten

### ISSUE THREAD

**Issue by tuxmatta** [puzzle-bbt/bbt#315]
Als **Kunde** möchte ich ein KeyResult (Resultat) erstellen und bestehende bearbeiten können, damit ich neue Resultate definieren kann.

* Wird in einem neuen Angular Modul umgesetzt.
* Der Pfad im Frontend ist:
  * `objective/1/keyresult/new`
  * `objective/1/keyresult/edit/42`

**KeyResult erstellen:**
![Screenshot from 2022-11-28 09-04-54.png](https://images.zenhubusercontent.com/61641bda09cd979ad092c0cb/0c2b9a51-e223-4ce1-aa4d-802e31e9d70a)

**KeyResult bearbeiten:**
![Screenshot from 2022-11-28 09-05-10.png](https://images.zenhubusercontent.com/61641bda09cd979ad092c0cb/98c6174b-1859-4219-9194-1a33216572f6)

* [x] Die Ausgabe entspricht dem ScreenShot 
* [ ] Die Knöpfe `Erstellen`und `Speichern` sind erst aktive, wenn das Formular valid ist.
* [x] Angular Komponente und das Template sind mit Jest getestet: Ist neu in der Story #339
* [x] Die benötigten Daten werden mittels Service + RxJS geladen.

**Comment by kcinay055679** [comment]
Branch https://github.com/puzzle/okr/tree/feature/315-KeyResult-form
