### ISSUE TITLE
OKR Frontend - Measure (Messung) hinzufügen + bearbeiten

### ISSUE THREAD

**Issue by tuxmatta** [puzzle-bbt/bbt#316]
Als **Kunde** möchte ich ein Measure (Messung) hinzufügen und bestehende bearbeiten können, damit ich die Messungen verwalten kann.

* Wird in einem neuen Angular Modul umgesetzt.
* Der Pfad im Frontend ist:
  * `/keyresult/42/measure/new`
  * `/keyresult/42/measure/edit/42`
* Nicht zu dieser Story gehören folgende ausklappbare Komponente:
  * Resultat Beschreibung
  * Vergangene Messungen
* Es wird eine neues Feld **Messungs-Zeitpunkt** unterhalb des **Aktuellen Wert** hinzugefügt, wo man das Datum der Messung definieren kann. Standardmässig ist es der aktuelle Tag. Als Widget auch ein Angular Material UI verwenden.
* Die Unit ist nicht zum Auswählen sondern wird nur angezeigt. 

**Measure hinzufügen:**
![Screenshot from 2022-11-28 09-16-00.png](https://images.zenhubusercontent.com/61641bda09cd979ad092c0cb/49247884-f051-46b2-b313-eb0a00d65117)

**Measure bearbeiten:**
![Screenshot from 2022-11-28 09-16-15.png](https://images.zenhubusercontent.com/61641bda09cd979ad092c0cb/71a48a9a-0775-4abb-9219-d6ce9ecd52dd)

* [x] Die Ausgabe entspricht dem ScreenShot 
* [x] Die Knöpfe `Erstellen`und `Speichern` sind erst aktive, wenn das Formular valid ist.
* [x] Angular Komponente und das Template sind mit Jest getestet
* [x] Die benötigten Daten werden mittels Service + RxJS geladen.

**Comment by lkleisa** [comment]
Ich habe die Änderungen auf den branch feature/316-measure-create-edit gepusht. 
Gemacht ist: 
- [x] Neuer Measure endpoint für eine Messung nach id zu holen
- [x] Neuer Measure Service im Frontend, welcher Messungen speichert und eine Messung nach id holt
- [x] Neuer Measure Form Component 
- [x] HTML des Form Components, mit Beispiel vom KeyResult Form 
- [x] Typescript mit voller Logik

**Comment by lkleisa** [comment]
Was muss noch gemacht werden: 

- [x] Negativ Test für Measure Service (404 zurück) 
- [x] Styling vom Form 
- [x] Ab und zu ist das Form invalid wenn man ein Measure bearbeitet
- [x] Bearbeiten von Measure ohne Date ändern funktioniert nicht, da das Date invalid ist
- [x] Tests für Measure Form Component
- [x] MeasureService save() methode testen
- [x] Smoke Testing

**Comment by lkleisa** [comment]
Es gibt ein Problem, dass die Tests vom MeasureForm im Intellij alle laufen, jedoch dann die Pipeline failed. Auch `npm test` funktioniert nicht. Wir haben es auf die Schnelle nicht hingekriegt.

**Comment by Vakmeth** [comment]
Die Tests haben bei mir lokal funktioniert, jedoch gab es noch einige Test welche fehlgeschlagen sind. Diese habe ich korrigiert.
Danach schlugen die Tests aber in der Pipeline fehl. Dies lag daran, dass wir in der Testklasse ein neues Date-Objekt generieren und die Zeitzone auf der Pipeline eine andere war als lokal.
