### ISSUE TITLE
OKR Frontend - Measure (Messung) - Resultat Beschreibung

### ISSUE THREAD

**Issue by tuxmatta** [puzzle-bbt/bbt#317]
Als **Kunde** möchte ich bei den Measure (Messung) eine Beschreibung zum dazugehörigen Resultat sehen, damit ich der Sinn der Messung besser verstehen kann.

* Das Diagramm gehört nicht zu dieser Story.

![Screenshot from 2022-11-28 09-26-51.png](https://images.zenhubusercontent.com/61641bda09cd979ad092c0cb/ffbf920a-3f3c-442a-89dd-abdea319a522)

* [x] Die Ausgabe entspricht dem ScreenShot 
* [x] Angular Komponente und das Template sind mit Jest getestet
* [x] Die benötigten Daten werden mittels Service + RxJS geladen.

**Comment by baeumelig** [comment]
Branch und Component ist erstellt.
Es braucht einen KeyresultService. So wie etwa 4 andere Stories.

**Comment by lkleisa** [comment]
Ich habe noch eine Änderung von Simons Code gemacht und dann die Tests dazu geschrieben, PR ist offen
