### ISSUE TITLE
OKR- Frontend  Objective Row Test

### ISSUE THREAD

**Issue by peggimann** [puzzle-bbt/bbt#321]
Als Entwickler möchte ich, dass meine Applikation zuverlässig funktioniert. Dazu will ich die entwickelten Features richtig testen, um zu wissen, ob der entwickelte Code funktioniert.

### Auftrag
Für das Feature Objective Row, sollen die Tests vervollständigt werden.

**Comment by MarcEgliP** [comment]
Vorgehen: 
- [ ] Überblick verschaffen, ob und wieviele Tests schon gemacht wurden.
- [ ] Nach vorgegebenen Muster die Tests nachschreiben.
- [ ] Tests ausführen überprüfen ob alle durchlaufen.
- [ ] Optimierung mit Prettier und Pullrequest stellen
