### ISSUE TITLE
OKR Frontend -  Fachbegriffe in englisch: Objective, KeyResults

### ISSUE THREAD

**Issue by tuxmatta** [puzzle-bbt/bbt#325]
Als **Kunde** möchte ich die beiden Fachbegriffe Objective + KeyResult in Englisch und der Rest in Deutsch angezeigt haben, damit um ein Durcheinander der Begriffe und Sprachen  zu vermeiden.

#### Akzeptanzkriterien
* [x] Das Frontend wird auf deutsch angezeigt.
* [x] Nur die beiden Fachbegriffe Objective + KeyResult sind in englisch.

**Comment by Vakmeth** [comment]
Beide Fachbegriffe wurden eingefügt, im Frontend sowie den Tests dazu

**Comment by Vakmeth** [comment]
Alles sichtbare bezüglich "Quartal" muss nach neuen Anforderungen noch zu "Zyklus" geändert werden.
