### ISSUE TITLE
OKR - Messung erhält neu ein Messungs-Zeitpunkt

### ISSUE THREAD

**Issue by tuxmatta** [puzzle-bbt/bbt#330]
Als **Kunde** möchte ich der Zeitpunkt einer Messung definieren können, damit ich Messungen nicht am selben Tag eintragen muss.

#### Anforderungen
* Backend und Frontend in derselben Story anpassen.
* Im Frontend wird das neue Feld `measureDate`verwendet.

#### Akzeptanzkriterien
* [x] Die Story ist wie beschrieben umgesetzt
* [x] Domain- und Model-Objekte erhalten ein neues Feld `measureDate` für den Messungs-Zeitpunkt vom Typ LocalDateTime
* [x] SQL-Daten sind angepasst.
* [x] Das neue Feld `measureDate` ist überall im Backend nachgezogen, auch bei den Tests.
* [x] Das neue Feld `measureDate` ist überall im Frontend nachgezogen, auch bei den Tests.
* [x] SQL der Progress-Berechnungen und letzte Messung herausfinden auch anpassen: Das neue Feld `measureDate` verwenden.

#### Anpassungen an der Story
_Anpassungen sind mit Jonas oder Paco vorab zu besprechen und an dieser Stelle einzutragen_

**Comment by kcinay055679** [comment]
DIe Arbeit wurde umgesetzt muss jedoch überarbeitet werden.
Github PR: https://github.com/puzzle/okr/pull/77](https://github.com/puzzle/okr/pull/77)
Diesem können die Punkte übernommen werden welche überarbeitet werden müssen.
Branch name: feature/330-measure-date

**Comment by kcinay055679** [comment]
Ich habe begonnen die angorderten Änderungen durchzuführen.
Folgende Änderungen müssen noch erledigt werden.
- [x] Backend Controller tests
- [x] Backend service tests
- [x] Fronend anpassen
- [x] Frontend Tests anpassen bzw erweitern
- [x] Frontend smoke tests

**Comment by lkleisa** [comment]
Ich habe die Frontend test angepasst und einen smoke test durchgeführt
