### ISSUE TITLE
OKR Backend: Neue Definition vom Quartal

### ISSUE THREAD

**Issue by tuxmatta** [puzzle-bbt/bbt#334]
Als **Kunde** möchte ich das Quartal in der Form `GJ 22/23-Q2` angezeigt haben, da man die Quartale auf dem Geschäftsjahr statt dem Kalenderjahr definiert.

**Hinweis:**
In Zukunft Sommer 2023 werden beim Zyklus/Quartal wahrscheinlich grössere Änderungen vorgenommen. Aus diesem Grund setzen wir die aktuelle Anforderung sehr einfach um.

#### Anforderungen
* Das Quartal kann bei einem PUT des Objective nicht mehr geändert werden.
* Wir ändern die REST-Schnittstelle bezüglich der Quartals-Information wie folgt: Statt `quarterId`, `quarterNumber` und `quarterYear` wir neu nur `quarterId` und `quarterLabel` verwendet, welcher das Quartal in der Form `GJ 22/23-Q2` überträgt.
* Jedes Quartal existiert nur einmal in der DB!

#### Akzeptanzkriterien
* [x] Die Story ist wie beschrieben umgesetzt
* [x] Unit- und Integrations-Tests sind nachgezogen
* [x] CodiMD anpassen
* [x] DB anpassen

#### Anpassungen an der Story
- Das Quarter kann ganz weg von KeyResult, da das KeyResult das Gleiche hat wie das Objective und wir es darüber holen können. 
- Wir generieren jetzt das Quarter neu im Backend und geben auf `/api/v1/quarters` alle 6 Quarters zurück (Aktuelle, 4 zurück 1 nach vorne). Entweder werden sie erstellt oder aus der DB genommen.
- Da wir das Quartal von der Java Klasse Calendar generieren, haben wir in der OkrApplication.java ein @Bean erstellt, damit wir diesen Calendar im Test dann überschreiben können und somit ein von uns gewünschtes Datum fest setzen können.

**Comment by lkleisa** [comment]
Die Logik funktioniert so wie sie soll. Niklas hat mit dem Frontend darauf gerebased. Folgendes ist gemacht / muss noch gemacht werden: 
- [x] Quarter auf KeyResult entfernen
- [x] Quarter Model  / DB anpassen
- [x] QuarterController 
- [x] QuarterService
- [x] Throw Error wenn Versuch Quarter zu ändern bei updateObjective
- [x] QuarterController Tests
- [x] QuarterService Tests
- [x] CodiMd anpassen

**Comment by lkleisa** [comment]
Das Quarter im Backend ist soweit fertig, alles ist getestet und hat 100% Testabdeckung. Jetzt warten wir auf ein Review, anschliessend das Quarter Frontend #335 abschliessen und dann beides hintereinander mergen
