### ISSUE TITLE
OKR Frontend: Neue Definition vom Quartal

### ISSUE THREAD

**Issue by tuxmatta** [puzzle-bbt/bbt#335]
Als **Kunde** möchte ich das Quartal in der Form `GJ 22/23-Q2` angezeigt haben, da man die Quartale auf dem Geschäftsjahr statt dem Kalenderjahr definiert.

**Hinweis:**
In Zukunft Sommer 2023 werden beim Zyklus/Quartal wahrscheinlich grössere Änderungen vorgenommen. Aus diesem Grund setzen wir die aktuelle Anforderung sehr einfach um.

#### Anforderungen
* Im Formular zum Ändern des Objective wird das Quartal nur noch angezeigt und ist nicht mehr auswählbar.
* Wir ändern die REST-Schnittstelle bezüglich der Quartals-Information wie folgt: Statt `quarterId`, `quarterNumber` und `quarterYear` wir neu nur `quarterId` und `quarterLabel` verwendet. 

```
{
    "quarterId": 42,
    "quarterLabel": 'GJ 22/23-Q2'
}
```
* Neuer QuarterService
* Objective-Formular Handling anpasen:
   * objective.service.ts
   * objective-form.component.ts + .html

#### Akzeptanzkriterien
* [x] Die Story ist wie beschrieben umgesetzt
* [x] Angular Komponente und das Template sind mit Jest getestet
* [x] Die benötigten Daten werden mittels Service + RxJS geladen.

#### Anpassungen an der Story
_Anpassungen sind mit Jonas oder Paco vorab zu besprechen und an dieser Stelle einzutragen_

**Comment by njaeggi** [comment]
Dieses Ticket ist abhängig von der Implemetation des Progress, welcher Marc noch anpassen soll in #342.
Dazu ist es noch abhängig vom Backend des Quarters, welches von Lias implementiert werden soll in #334.

Der Code und die Tests stehen, die Dinge die nicht funktionieren sind aktuell auskommentiert, ich werde diese am Donnerstag (falls die oben genannten Tickets beendet sind noch implementieren und somit die Änderung des Quarters vollständig abschliessen.

Wichtig:
Falls Yanick die Objective Form Tests abschliesst, muss bei dieser noch angepasst werden (dies werde ich machen, wollte es trotzdem erwähnt haben)
