### ISSUE TITLE
OKR Frontend - KeyResult (Resultat): Testing

### ISSUE THREAD

**Issue by tuxmatta** [puzzle-bbt/bbt#339]
Als **Entwickler** möchte ich das Feature _OKR Frontend - KeyResult (Resultat) erstellen + bearbeiten_ getestet haben, damit wir die Funktionstüchtigkeit sicherstellen können.

#### Akzeptanzkriterien
* [ ] Angular Komponente und das Template sind mit Jest getestet

**Comment by njaeggi** [comment]
Letzter Test wird am Montag mit Hilfe von Jonas überabeitet.

**Comment by njaeggi** [comment]
Es wurde ein Review von Jonas gemacht, dies haben wir noch nicht implementiert. Dieses Ticket sollte noch von mit oder Lias abgeschlossen werden, da wir die Tests geschrieben haben.

Wichtig:
Manche Tests werden noch geskipped und sollten noch gefixt werden, ausserdem sollten Dropdown Tests auf Harness umgeschrieben werden und auch leere Tests sollten noch implementiert werden
