### ISSUE TITLE
OKR - Enum in der REST-Schnittstelle

### ISSUE THREAD

**Issue by tuxmatta** [puzzle-bbt/bbt#340]
Als **Entwickler** möchten wir das Handling mit den Enum's in der REST-Schnittstelle vereinheitlichen, damit wir nicht mit Enum-IDs (Index) arbeiten müssen.

#### Anforderungen
* Die Schnittstelle verwendet keine Enum's mehr, sondern neu nur noch das Label/Name des Enum.
* SwaggerUI aktualisieren

#### Akzeptanzkriterien
* [ ] SwaggerUI ist aktualisieren

**Comment by njaeggi** [comment]
Swagger Doku muss nicht aktualisiert werden, da die Enums strings und indexe akzeptieren, jedoch sollte ein Integrations Test erstellt werden der beide Fälle einmal testet, bedeutet einmal ein string abschicken und einamal den index des enum

Werde dies am Donnerstag implementiern, falls dies niemand übernimmt :)
