### ISSUE TITLE
OKR Frontend - Tests werden in der Github-Pipeline nicht ausgeführt

### ISSUE THREAD

**Issue by tuxmatta** [puzzle-bbt/bbt#341]
Als **Entwickler** möchte ich die Frontend Tests in der Github-Pipeline ausgeführt haben, damit man fehlerhafte Tests nicht einchecken kann.

#### Akzeptanzkriterien
* [x] Die Github-Pipeline führt die Frontend Tests aus.
* [x] Wenn nicht alle Frontend Tests funktionieren, schlägt die Github-Pipeline fehl.

#### Anpassungen an der Story
_Anpassungen sind mit Jonas oder Paco vorab zu besprechen und an dieser Stelle einzutragen_

**Comment by lkleisa** [comment]
Pipeline enthält nun noch die Frontend Tests (npm test). Sie wird bei jedem Push ausgeführt und schlägt fehl wenn ein Test failt
