### ISSUE TITLE
OKR Backend - Progress-Berechnung fixen

### ISSUE THREAD

**Issue by tuxmatta** [puzzle-bbt/bbt#342]
* Zur richtigen Zeit anstossen
* Richtig berechnen
* Testen
* checkObjective in objectiveservice soll keine Exception werfen wenn progress null ist für die Bearbeitung von Objectuves, für genauen Grund kannst du Jonas fragen :)

**Comment by njaeggi** [comment]
Bei der Berechnung des Progress sollte am Anfang beim erstellen des Objectives die Zahl 0 als Progress gesetzt werden. Egal was vom Frontend kommt. Auch bei einem update sollte eine Exception geworfen werden falls der progress nicht null ist. In der checkObjective() Methode muss die Überprüfung für den Progress überarbeitet werden (null ist möglich)

**Comment by Vakmeth** [comment]
Vorgehen Teil1:
- [x] Progressüberprüfung in checkObjective() Methode löschen
- [x] Committen & Pushen
- [x] Draftpullrequest erstellen

**Comment by Vakmeth** [comment]
Vorgehen Teil2: Progress in Objectives auf 0 setzen
- [x] In ObjectiveService bei der saveObjective() Methode mit Setter progress auf 0 setzen.
- [x] Tests durchlaufen lassen, korrigieren wo nötig
- [x] Committen & Pushen

**Comment by Vakmeth** [comment]
Vorgehen Teil2: Richtig berechnen
- [x] Ursache für die Fehlberechnung suchen
- Ursache liegt im Startwert, dieser wird aus irgendeinem Grund in die Berechung miteinbezogen
- Korrigiere: Es war so angedacht, dass der Startwert in die Berechnung einbezogen werden muss, wird nun im Query ergäntz
- [x] Query demnach verbessern
- [x] Tests durchlaufen lassen, korrigieren wo nötig
- [x] Committen & Pushen

**Comment by Vakmeth** [comment]
Stand des Tickets:
- Ich konnte den Progress aus der checkObjective() Methode löschen, somit werden null-Werte für den Progress im POST angenommen
- Die Tests habe ich gelöscht und durch einen Test ersetzt, welcher Mockito verwendet
- Den Bug welchen @njaeggi und @lkleisa entdeckt haben, konnte ich leider nicht reproduzieren, evtl. wurde dieser schon durch die voorigen Schritte ausgemerzt.
- In der Progressberechnung habe ich den Basiswert nun in die Berechnung einbezogen und im Frontend musste ich eine Bedingung ändern da mit dem || Operator gearbeitet wurde und dieser bei 0 einen false Wert erkennt

=> Somit kann das Ticket gemerged werden
