### ISSUE TITLE
OKR Backend - Integrations Tests von Objective Controller 

### ISSUE THREAD

**Issue by peggimann** [puzzle-bbt/bbt#346]
Als Entwickler, will ich das die Applikation vollstäjndig auf ihre Funktionalität getestet wird, damit ich stehts weiss, das alle gewünschte Funktionalität vorhanden ist. 

### Auftrag
Beim Objective Controller, wurde das falsche Mapping verwendet, es wurde @RequestBody von Swagger verwendet, anstelle der richtigen @RequestBody von Spring. Nachdem dieser Fehler aufgefallen ist und korrigiert wurde, funktionieren die Integrationstests für das PUT- Mapping nicht mehr auf dem Objective, diese gilt es nun zu reparieren. 

### Akzeptanzkriterien
 - [x]  Alle IntegrationsTests auf dem Objective funktionieren wieder ordnungsgemäss

### Weiteres

_Jegliche Änderungen an der Projektstruktur sind zuerst mit Jonas oder Paco abzusprechen_

**Comment by njaeggi** [comment]
Orientierung an den KeyResult Tests von @njaeggi im KeyResultControllerIT

**Comment by Vakmeth** [comment]
Stand des Tickets:

- Alle Tests wurden gefixt und laufen nun wieder
- Es musste ein Body mitgegeben werden, damit das PUT von der API akzeptiert wird, andernfalls hat sie einen 400 zurückgegeben.

=> Ticket kann gemerged werden
