### ISSUE TITLE
Mail Retriever Job

### ISSUE THREAD

**Issue by lucashabersaat** [puzzle-bbt/bbt#36]
Dieser Job wird regelmässig ausgelöst und startet den BulkMailRetriever, welcher Mails abruft, als Messages und E-Mail in FileStore speichert, ...
Er soll implementiert und getestet werden. Am besten gleich _test-driven_.

MailingList::MailRetrieverJob erstellen, leere Klasse MaillingList::BulkMailRetriever erstellen mit Methode perform (Implementation ab #50)

# Tech Spec

## Bestehend

Derzeitiger MailRelayJob 
app/jobs/mail_relay_job.rb

app/domain/mail_relay/base.rb
app/domain/mail_relay/lists.rb

## Neu

MailingList::MailRetrieverJob (recurring job)
app/jobs/mailing_list/mail_retriever_job.rb  

MailingList::BulkMailRetriever
app/domain/mailing_list/bulk_mail_retriever.rb

**Comment by miosidler** [comment]
[Pull request](https://github.com/hitobito/hitobito/pull/1234)

**Comment by miosidler** [comment]
[new PR](https://github.com/hitobito-bbt/hitobito/pull/2)
