### ISSUE TITLE
Puzzle Inside /bbt

### ISSUE THREAD

**Issue by Robin481** [puzzle-bbt/bbt#370]
Da müssten wir mal unser Konzept ausarbeiten und ausdenken was wir machen können.

Vermutlich ist es spannend für die Puzzle Members ein Einblick ins BBT zu bekommen den sie sonst nie kriegen.
Ähnliches wie die Elternabend Vorträge bei denen ihr über die Schule o.ä. erzählt ist sicher spannend.

Random Fun Idee:
- Ein Kahoot mit Fragen die ihr in der Schule beantworten müsst, nicht zwingend nur Informatik... Franz? :grin:  (lustig weil vermutlich viele vieles nicht mehr können).

**Comment by Vakmeth** [comment]
Codi mit Themengebieten für das Kahhot und dem Ablauf: https://codimd.puzzle.ch/flAkw2XwSk-p9u-LNZP_0Q#

### Aufgaben
- [ ] Alternative zu Kahoot suchen um fragen aufzulisten

**Comment by RandomTannenbaum** [comment]
**ToDo**
- Ticket bei SyS für Beamer setup etc.
- Znüni von Marketing
