### ISSUE TITLE
IMAP_CLIENT: finissshhhhhhh

### ISSUE THREAD

**Issue by psunix** [puzzle-bbt/bbt#59]
PR: https://github.com/hitobito/hitobito/pull/1259

Folgende Punkte sind noch für den Imap Client anzupassen **feature/30-catch-all**  :rocket: 

Weniger tests die dafür gleich die komplette implementation testen. grundsätzlich sollte man keine privaten methoden testen. es gibt natürlich ausnahmen und je nach komplexität kann das sinn machen.

# Routen

Routen anpassen, für alle routen /mailing_lists/imap_mails/:mailbox als base verwenden

REST standard für routen!

- [x] index: /mailing_lists/imap_mails/:mailbox
- [x] delete /mailing_lists/imap_mails/:mailbox, param mail_ids
- [x] move /mailing_lists/imap_mails/:mailbox/move, sep param dst_mailbox (zielmailbox, source mailbox aus :mailbox), param mail_ids

# /app/utils/imap Imap::Connector

- [x] spec/utils/imap/connector_spec.rb erstellen (move spec/utils/imap_connector_spec.rb
- [x] specs anpassen: #fetch_mail -> soll liste mit Imap::Mail objects zurück geben
- [x] falls möglich select folder nicht in instanzvariable, braucht es das?
- [x] in spec: connection block entfernen und die funktionalität z.b. über fetch_mails sicherstellen
- [x] braucht es stub_const? sonst entfernen
- [x] grundsätzlich nur test für public methoden in spec, alles andere soll implizit getestet werden (einfach die funktionen testen die effektiv verwendet werden, less is more -> lieber ein einzelner test case der z.B. fetch_mails testet und das gleich inkl. connect, disconnect, folder create, usw.

# /app/utils/imap Imap::Mail

- [x] initializer nimmt raw mail von Net::IMAP entgegen und instanziert ein entsprechendes Mail object
- [x] ggf. sep. spec dafür erstellen, alternativ kann das auch im connector spec gemacht werden?

# /app/controller/mailing_lists/imap_mails_controller.rb

- [x] params standardisieren: params[:mailbox], params[:mail_ids] für mail ids
- [x] controller specs -> ein context block für jede action: move, delete, index
- [x] Ability ggf. noch anpassen. VariousAbilty https://github.com/hitobito-bbt/hitobito/blob/feature/30-catch-all/app/abilities/various_ability.rb#L27

Sicherstellen das in allen Files der richtige Lizenzheader mit Hitobito AG und frozen_string... vorhanden ist. encoding utf8 weglassen!

**Comment by luca-bruegger** [comment]
**Update 16.4.2021: Was noch fehlt @miosidler **
imap_mails_controller_spec.rb            -> DELETE #destroy Testcases
imap_mails_move_controller_spec.rb -> PATCH #create     Testcases
Sidenav bug im UI
Pills Im UI, tipp: Probieren mit Admin und hitobito@puzzle.ch Users

Zum Abschluss:
Schauen ob alle pry's und Kommentare entfernt wurden.
Eventuell bessere namings finden.

**Comment by miosidler** [comment]
[Draft PR](https://github.com/hitobito-bbt/hitobito/pull/3)  
WIP imap_mails_controller, imap_mails_controller_spec
