### ISSUE TITLE
CRYPTOPUS: Getting started

### ISSUE THREAD

**Issue by mtnstar** [puzzle-bbt/bbt#81]
Mit Cryptopus vetraut machen, Rails Tutorials durcharbeiten, Ruby kennenlernen, Hello EmberJS ...

**Comment by njaeggi** [comment]
Finished reading the Rails Guide
https://guides.rubyonrails.org/getting_started.html

**Comment by lkleisa** [comment]
I've done the same tutorial as Niklas and also tried this for ember:
https://guides.emberjs.com/release/tutorial/part-1/
Made also a small rails project by myself
